#define MAX_ENCOUNTER_TYPES			14

// Encounters types
#define ENCOUNTER_TYPE_MERCHANT0			0
#define ENCOUNTER_TYPE_MERCHANT1			1
#define ENCOUNTER_TYPE_MERCHANT2			2
#define ENCOUNTER_TYPE_PATROL				3
#define ENCOUNTER_TYPE_FLEET				4
#define ENCOUNTER_TYPE_CORSAR				5
#define ENCOUNTER_TYPE_PIRATE				6
#define ENCOUNTER_TYPE_PUNITIVE_SQUADRON	7
#define ENCOUNTER_TYPE_MERCHANT3			8
#define ENCOUNTER_TYPE_FLEET2				9
#define ENCOUNTER_TYPE_FLEET3				10
#define ENCOUNTER_TYPE_PIRATE2				11
#define ENCOUNTER_TYPE_ARMADA				12
#define ENCOUNTER_TYPE_MERCHANT4			13

// Encounter type
#define ENCOUNTER_TRADE				0
#define ENCOUNTER_WAR				1

object EncountersTypes[MAX_ENCOUNTER_TYPES];
