string DLG_TEXT[37] = {
"Thank you, kind stranger. Nigel Blythe was always quick to retaliate, and if you hadn't intervened, I certainly wouldn't have been saved.",
"Yes, I noticed you were having some sort of disagreement.",
"Yes, I noticed you were having some sort of disagreement.",
"I was the navigator on Nigel's ship. He didn't know much about the sea. Not long ago, we were carrying a very large cargo, and we were also sailing to an unfamiliar island\nWe survived the storm, but it destroyed the cargo and the ship, so when we arrived here, Nigel threatened me and then he got so angry that he almost killed me.",
"So now you're left without a captain.",
"By the way, I still don't know your name. My name is ",
". ",
"My name is Artois Voisier, and I have indeed become a land rat. I would be happy to serve you if you find me useful.",
"Thanks, but I've already have a navigator.",
"Wellcome aboard. But please, try not to sink my ship too.",
"What do you want, Captain?",
"Well?",
"Just passing by.",
"At ease.",
"Let's talk about our tactics during the boarding.",
"Captain? It's you! Thank you for your help\nThose bastards killed my friend... an old friend, and wanted to kill me also...",
"Yes, of course. But answer me - why were they attacking you in the first place?",
"I can't answer you that. It's someone else's secret, I'm bound by oath and I can't tell you about it.",
"I think you misunderstand me. I am your captain, and you must obey me in all things. And if you don't want to end up dead, you'll tell me quickly!",
"Alright, Artois, I always knew you were a man of honour. Keep your secret to yourself.",
"Since you're treatening me... Well, I'll tell you the secret\nSomehow, Nigel Blythe learned of a shipwrecked near Conceicao, carrying treasure in its hold. We were headed there when we were shipwrecked ourselves\nWhen you killed Nigel, I became the only man alive who knows the way to this treasure. That's why Blythe's former crew is after me\nThe secret is this - the treasure is located on Douwesen. You can find the path to the wrecked ship under the waterfall.",
"Now we're talking!",
"Thanks, Captain. I knew I could count on you.",
"You're welcome. Glad to see you alive and well.",
"Is something else bothering you?",
"Yes, I've fallen into disgrace with local authorities because of this mess...",
"Oh, don't worry, I think I can take care of this problem.",
"That's right, you're - we might say - a witness to the whole thing.",
"Thank you, Captain! You've saved my life once again. Now I believe I can tell you my secret\nDuring our voyages, we boarded a Spanish galleon loaded with gold near Conceicao, but we shipwrecked\nWhen you killed Nigel, I became the only man alive who knows the way to this treasure. That's why Blythe's former crew is after me\nThe secret is this - the treasure is located on Douwesen. You can find the path to the wrecked ship under the waterfall.",
"Thank you for your confidence, Artois",
"Just one request, captain. I've sworn that if I make it out of this adventure alive, I would donate 4000 piastres to the church in Redmond.",
"Of course, we'll do it! Now let's be on our way.",
"Yes, I'm listening.",
"I don't want you to come aboard with me.",
"I want you to come aboard with me.",
"Alright, Captain.",
"...",

};