string DLG_TEXT[238] = {
"I'll ask you to kindly leave my house this instant. I'm busy.",
"...",
"So, Governor ",
"Robert Christopher Silehard",
" sends me his right-hand man. What does he want from me, boy?",
"Who says I work for him?",
"What makes you think I'm here on the governor's orders?",
"I beg your pardon, but do I look like the village idiot? The moment I learned someone was looking for me, I made inquiries\nWould you look me in the eye and deny you've been working for him for the past several months?",
"Okay, let's say you're right, and the governor sent me. What difference does that make? Would you refuse to talk to a representative of the governor?",
"Look, I've had about enough of this cat-and-mouse. Are you going to talk with me, or would you rather choose which of your legs you want to keep?",
"Captain, I wonder if you know who you're speaking to. You must trust me when I say that if I didn't want to talk to you, you would not be standing here.",
"Oh, there's no need for physical violence, boy. I'll speak with you because I'm curious: What does that old fox, the governor, want from me?",
"Fine. I need to know where I can find a gentleman by the name of ",
"Raoul Rheims",
". I know he's hiding somewhere on this island.",
"Your information is out of date, young man. ",
"Raoul Rheims",
" did indeed spend a couple of days here. Virtually never left his house\nBut he's already set sail again, and he kept his destination secret even from me. Clearly, he was worried about something, but I couldn't say what.",
"He has a house here? Where can I find it?",
"Has a shack here on the island, does he? Where is it?",
"Just a moment, boy. You may well be an envoy of the English governor, but that doesn't give you leave to invade another man's home and paw through his belongings. Do I make myself very clear?",
"I beg you to make an exception for me, sir. I must find out where ",
"Raoul Rheims",
" was sailing to, and soon!",
"Oh, come now. You're a smuggler, known all over the archipelago for your lack of principles. You're going tell me about the law?",
"I can see you won't listen to reason. If I can't convince you to stay away from that house, I'll simply order my men to stand watch over it and shoot on sight. I'm sure even you can take a hint from a musket ball. Now, go!",
"Goodbye.",
"This isn't over!",
"Please leave my house. I'm busy and I don't have time to talk to you.",
"...",
"So, you have responded my request. I'm very glad for that...",
"I hope this whole invitation thing isn't going to get back at me for break-in into Rheims' house!",
"So, have you come to accept my offer?",
"Yes, I think it suits me.",
"No... I'm still thinking about it.",
"Well, let's see... No, you still can't get the right amount of cargo on board.",
"All right, I'll take that under consideration.",
"Well done! I see you've managed to unload the hold. You're good to go on my mission.",
"Looking forward to it.",
"Where the hell have you been all this time, ",
"?!",
"Trying to find a bigger ship.",
"You are back! Good! Well?... I can tell by the look on your face that something happened.",
"Alas, I don't have good news. The deal went through, but before Matton handed me the money, he was arrested by soldiers.",
"You're back. Do you bring good news and the money?",
"Yes, although that bastard, Arnaud, set me up in a big way.",
"You're back. Do you bring good news and the money?",
"Alas. I have proof that indeed was Arnaud who hide the cargo.",
"You're back. Do you bring good news and the money?",
"No, I don't bring the money. Arnaud asked for a reprieve, and then that bastard send his murderers on me!",
"You're back. Do you bring good news and the money?",
"No, I don't bring the money. Arnaud is on the verge of bankruptcy and couldn't pay for our shipment, which was also confiscated from him.",
"You're back. Do you bring good news and the money?",
"Yes, although that bastard, Arnaud, send murderers after me.",
"Well, well, well... Look who is here! Why are you so early? You could have stayed away for another 2 or 3 years...",
"I was caught in a storm! No... I almost got eaten alive by a shark!",
"You've arrived just in time, my friend. Now, let's talk to the leader of the pirates. Please don't interfere unless you have to.",
"All right, I'll keep my mouth shut.",
"The devil! I had hoped that all the issues would be resolved during this meeting, but there's even more!",
"And what are we going to do next?",
"I can tell by the look on your face, that you didn't come back empty-handed.",
"And you're darn right I didn't! Here's the paperwork for the shop.",
"You look like a a mess, Nathaniel. Is something wrong?",
"(You recount in detail the incident on Falaise de Fleur to Machado, alternating with speculation about Arnaud Matton's pedigree).",
"You look like a mess, Nathaniel. Is something wrong?",
"(You recount in detail the incident on Falaise de Fleur to Machado, embellishing the reality a little, so as to not look like a complete idiot in the eyes of your employer).",
"Your gloomy appearance tells me that you've come back with nothing... Tell me what happened.",
"(You tell Machado the details of your failed adventure).",
"Your gloomy appearance tells me that you've come back with nothing... Tell me what happened.",
"(You tell Machado of your failure).",
"Why have you returned so quickly? Did you fulfilled my errand?",
"Not yet, but I have news for you. Quite unpleasant ones.",
"It's good to have you back! I have everything ready. We can begin.",
"Godspeed!",
"Yes, you're a quite a swordmaster. I've seen the whole thing myself, it was an spectacle!",
"Thank you.",
"I regret to tell you this, but by killing Barrakuda you have lost all credibility on my part.",
"",
"God be with Rheims, but we're not talking about him. Although, it was your impertinent intrusion into his house that prompt this conversation.",
"Ahem... Go on.",
"How would you feel about the possibility of joining us? My men risk their necks, but they make good money. And you, with your talents, are quite capable of becoming my associate... in the future. What do you say?",
"It's a tempting offer... I think I'll take it.",
"Thanks, but I'm not interested.",
"That's too bad... But I'm a patient man, if you change your mind, let me know.",
"Time will tell. Farewell.",
"That's great! Let's get down to business then, let me be clear from the start that I don't care what flag you fly, or whom you quarrel with. All that matters is that you follow my orders...",
"Sounds like you are offer me to be your errand boy.",
"No offence, my friend, but in order to be my associate you will have to work hard. And it won't always be a pleasant job.",
"You told me that already... Very well, what do you want me to do?",
"To deliver contraband, of course... But don't smile like that, please. You may have smuggled before, but this time is different.",
"Sorry, I couldn't resist. Indeed, what else can smugglers do, but to deliver contraband.",
"You are mistaken, friend, and soon will find out. Not all my errands are bleak and monotonous tasks. Anyway, let's get back to business, shall we?",
"Yes, I suppose that would be the best.",
"Don't be sarcastic, ",
"! Your chattering is beginning to bore me!",
"You're the one who offered me this job! So, if you want me, you'll have to put up with my manners as well.",
"I'm already starting to regret my offer...",
"God have mercy! Shouldn't you be concerned that I follow your orders rather than the way I speak?",
"I'll think about it... later. For now let's continue with our business\nYour task is to deliver a shipment of sandal to Arnaud Matton, the shopkeeper on Falaise de Fleur. Don't worry, he's been informed, and the risk is no more than the usual. On your return, you will receive your payment.",
"Hmm... Alright, we'll see about that!",
"However... your ship is not large enough to do serious business. Make some room in the hold and come back. Perhaps carrying sandal will also be necessary.",
"I will do that. See you later.",
"Let me check... Alright, your ship's hold can easily accommodate all the cargo.",
"That's great! When can I set sail?",
"Don't be in such a hurry, ",
". Let me remind you again what you have to do. So, Falaise de Fleur Island, Arnaud Matton's shopkeeper, reward when you return.",
"Falaise de Fleur, Matton, money. Yes?",
"Indeed. Good luck to you my friend.",
"As they say, fortune favors the bold.",
"Whatever... just hurry! If not, I can get someone else to do the job.",
"I'll be back as soon as I can.",
"We could go to Europe - there's a excellent selection of ships with enough hold for any kind of voyage...",
"Aha!, I assume someone else took the sandal to Falaise de Fleur?",
"Yes, I couldn't wait any longer. As you know, every shipment has it's deadline.",
"Hmm... What am I supposed to do now? That's it? I'm free?",
"No, no, take your time! Maybe I overreacted by shouting at you, but... Anyway, we've had some problems with this sandal...",
"Ha! What are they?",
"The deal went bad... My man unloaded the sandal to Matton, but when he went to his shop to collect the money, French soldiers burst in. My man was forced to retreat in haste, pretending to be a regular customer, but he saw through the window that the soldiers had found the hidden sandal and arrested Arnaud.",
"And what can I do?",
"Hmm... Tell me more about this incident.",
"(You tell him exactly what happened at Matton's shop).",
"Hmm... It's not your fault that you didn't finish the assignment. So, here's your reward.",
"Thank you... Can I do something about this situation, after all?",
"Oh, you will! I'll send you to Falaise de Fleur once more.",
"Of course... What is it? Do you have some sort of plan?",
"I have a feeling that something isn't right here. Matton hasn't been straight before, and that worries me.",
"Are you saying that this crook put up a show just to avoid paying you?",
"I have that suspicion, yes. But it's up to you to find out if that's true!",
"Not just for 'thank you', I suppose?",
"Have you forgotten? I told you I reward my men generously.",
"I haven't forgotten, I just think you are even more slippery than this Matton.",
"I'll kindly ask you, ",
"... don't forget who you're talking to!",
"Alright, alright, get my reward ready. I'll squeeze what I can out of that scoundrel.",
"I want the sandal or the money back. Remember it. I don't care how you obtain either of both.",
"All right, farewell.",
"Hmm... So he decided to play me... Are you sure of his guilt?",
"Absolutely sure! The bastard planted the ring on me, and then claimed I stole it.",
"All right, I'll think of a way to teach that bastard a lesson... Did you give me my money back?",
"Here it is.",
"Great, and here's your percentage of the deal. Now I'd like to ask you one more job to do.",
"What can I do for you?",
"Well, that's a result too. I'll tell you more.",
"(You tell Machado in detail the story of your captivity and fortunate release).",
"Hmm... Well, I'll think of a way to teach this rascal a lesson... In the meantime, I'd like to assign you one more job.",
"What can I do for you?",
"Hmm... Do you have any proof that these men were acting under the orders of Matton?",
"Who else would want to get rid of me?",
"I don't know about that. Alright, I'll think about this situation for a while, but in the meantime I have a new assignment for you.",
"What can I do for you?",
"And I take it you haven't conducted any investigation into this? That kind of credulity gives you no respect.",
"But, allow me!",
"Shut up! I'll send someone else to check on that rascal. I have another assignment for you.",
"What can I do for you?",
"Tell me more about what happened.",
"(You tell Machado what happened at Falaise de Fleur).",
"Alright... I'll see what I can do with that scoundrel, but in the meantime, I have a new assignment for you.",
"What can I do for you?",
"I need your help. The relations between us and the pirates of Quebradas Costillas have become somewhat strained lately...",
"And?...",
"...and I've arranged a meeting with the head of the pirates, ",
"Isenbrandt Jurcksen",
"...",
"Aha, and I have to be present to provide your security?",
"Security?! Are you kidding, ",
"Ahem... I see. Well, an extra is an extra. Now, please, tell me more.",
"You're going to set course for Douwesen. We'll meet at the cove known as the 'Crab's Cliffs'. Oh, and don't be late, the appointment is scheduled in two weeks.",
"I won't.",
"You were joking?! I wasn't in the mood for jokes, by the way! You almost ruined my negotiation, so keep in mind, one more slip-up and I'll have to break up with you.",
"I get it.",
"I think you spent all the time at the port whore's house\nAnyway, you failed the previous two tasks, and you failed the third one! So why don't you go to hell instead?",
"What?! How dare you to talk me like that, you bastard!",
"I'm sorry about the way things turned out.",
"You will answer that insult, scurvy dog! Defend yourself!",
"Massive, you say, escort... I'll show you both an escort and a massacre! Argh!",
"Likewise. Wish you all the best. Good-bye.",
"Farewell.",
"To think... I'll be the one thinking, and I've got a new assignment for you.",
"What is it?",
"If you remember, we had a problem with Arnaud Matton...",
"Of course! That scoundrel caused me a lot of troubles!",
"Do you remember Arnaud Matton? After you couldn't pay me back, I sent another man to that merchant\nAnd as I was informed today, that the man was executed.",
"The devil! So it's true that it wasn't straight!",
"We need to teach him a good lesson. Namely, you must make him sell his store to one of my men. How exactly you do it, is of no concern to me.",
"You can be sure I'll handle this assignment.",
"You've done me a great service, my friend. Here is your reward, and I have a new task for you.",
"And what is that?",
"I'm sorry to hear that. I'll have to assign to someone else the task to buy the store, which will entail additional expense.",
"I did my best, but the man was easier to kill than to persuade.",
"I'm afraid that's the end of our partnership, ",
"Blasted hell! I almost lost my head, and you're still worried about some damn store!.",
"I'm sorry about the way things turned out.",
"Don't be upset, everyone has a slip-up. Now back to business, I have a new assignment for you.",
"What is it?",
"I beg your pardon! You're not talking to the longshoreman, are you?",
"That's it! I'm tired of your lectures! You've had enough in this world!",
"Likewise. Wish you all the best. Good-bye.",
"Farewell.",
"Really, ",
"And what is it about?",
"As you may recall, we had problems with the pirates, with both leaders denying any involvement...",
"Yes, I remember everything.",
"We have a problem with pirates... Or rather people who hoist the pirate flag, but are not members of the coast brotherhood.",
"Continue.",
"I've managed to find out that the local governor is to blame for what's going on. He has a fleet of 5 warships to fight my men...",
"You want me to deal with this fleet??",
"Exactly. And I will reinforce your convoy with my own men.",
"Alas, I can manage just fine on my own!",
"I'm afraid that's out of the question. Now let me introduce you to your companion.",
"...",
"Don't waste time, tell me what you've learned.",
"We have a traitor in our ranks!",
"Aha... From now on, more details.",
"(You tell Machado everything you learned in the tavern).",
"Damn it! Alright, I'll deal with it, while you continue with your assignment.",
"Fine. But I like to suggest a plan of my own.",
"I'm listening.",
"Tell your people about a big deal coming up.",
"I see your point. The traitor will inform the governor, and he will arrange a squadron to intercept my men.",
"Exactly!",
"Good plan. But it will take me at least a week to prepare it.",
"I will wait. Get your men ready.",
"Don't be modest, ",
"Yes, What can I do for you?",
"You have honourably completed all my assignments, and as I promised you can take my associate's place.",
"I accept your offer, boss.",
"I think I'd better take your place, you rascal!",
"I promised you I'd make you my associate, but I have to disappoint you...",
"You scum! I've been doing your errands for nothing? No, I haven't! Defend yourself!",
"It's unfortunate that you had made that choice. You can try to kill me, but know that my people won't accept you anyway.",
"Who cares?",
"It's unfortunate that you had made that choice. You can try to kill me, but know that my people won't accept you anyway.",
"Who cares?",
"I'm glad of that. Well, good luck with that.",
"If you need anything, you're welcome.",
"? No, I need you as an extra, an entourage, for more authority, so to speak.",
" you've outsmarted yourself. I shall send someone else to settle this matter. I have a new assignment for you.",
", I'm delighted with your actions, but now we need to discuss another important matter.",

};