string DLG_TEXT[27] = {
"I am told you went to great lengths to speak with me. My name is ",
". And now, will you please tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it is you again? Why are you here this time?",
"I'd like to do a little business with you.",
"I'm terribly sorry, but I have more important things to do.",
"So, why do you come here and distract me from important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"Just a polite visit, senor, nothing more.",
"In that case, please leave my study and let me get back to my work.",
"Yes, of course. Sorry I disturbed you.",
"As you English say, I am all ears, ",
".",
"...",
"Yes, I have a job for you, Capitan.",
"And what is that?",
"I've already been informed hat you have completed my mission. Congratulations, here's your reward.",
"Thank you, senor. It's been a pleasure serving you.",
"I need you to sink the ship '",
"quest pirate",
"', presumed to be sailing around the colony of ",
". If you complete this mission, I will pay you ",
" gold pieces.",
"I'll take the assignment.",
"Sorry, but I'm not interested.",

};