string DLG_TEXT[84] = {
"...",
"...",
"Boy, you wouldn't happen to be the captain, would you? There's something about your demeanour.",
"You're right. I am indeed a captain. Why do you ask?",
"I don't talk to any suckers. Get lost!",
"You boor!",
"This might just be a lucky day for both of us. I'm preparing to undertake a venture, and I'm looking for a partner.",
"And what kind of venture is that?",
"A very profitable one, I'd say. How do you feel about laying your hands on a few dozen pounds of gold?",
"How do I feel about it? Strictly positive, of course!",
"Sorry, but I don't think I'm interested.",
"Ha! I knew you were the man for the job. So here's the deal. All we have to do is land in one secluded spot, and get the gold. Genius plan!",
"Yeah, sounds like a masterplan. First of all, land where? Secondly, who's guarding this gold of yours?",
"It's not mine, it's ours, you're in on it now! And the rest doesn't matter. I'm sorry, but I don't trust you enough to tell you everything at once.",
"Fair enough. Okay! when do we sail?",
"Sorry, but I don't think I'm interested.",
"The sooner the better! Get out to sea. I'll join you, and we'll set course for Oxbay.",
"All right. I'll finish my business here, and I'll join you. By the way, on what terms?",
"On the usual - we divide the spoils equally between our crews.",
"Fair enough. All right, see you at sea.",
"Here we are! Half-done, just grab the mines and we'll have the gold in our hands.",
"English gold...",
"Yes?",
"No, nothing.",
"I understand. I don't want to quarrel with the English either. But if we do it right, they will never know.",
"You're suggesting we just cut everyone out?",
"Exactly!",
"All right, then go ahead!",
"Yo-ho! That's a good one!",
"Yeah, except I don't see any gold.",
"Blast! They've already shipped it away. Hurry - the cart tracks are still fresh. We can still catch up with them. I'm sure they're taking the gold to Oxbay, as always.",
"All right, let's try and catch up with them. We've come too far, it would be foolish to turn back now.",
"No! I've had enough! I'm leaving, and to tell you the truth, I'm very sorry I got involved in this adventure.",
"God be with us! If we capture this convoy, I'll personally present the church with a huge golden cross!",
"Enough talk, time is of the essence!",
"No! You're not getting away that easily, we're tied now! Either you help me or I'll kill you where you stand!",
"Well, try it! Let's see what's inside you!",
"All right, all right, let's not fight. I'm with you.",
"There they are! We've got to stop them from getting away!",
"Onward!",
"Blast! We lost them! Now we'll have to leave with nothing.",
"And leave fast, before they send a chase after us!",
"We did it!",
"Yes, only now we have to leave at once, and there's no way to get back to the ships.",
"I know! We'll have to think of something - it would be a shame to lose such booty.",
"We could send some of our men to the ships. There's a cove not far from here, let them go in there.",
"We'll do that. Now quick, let's go!",
"...",
"We're in the right place, but I can't see our ships. We'll have to wait.",
"Quiet. I hear voices... We've got company, get ready to fight!",
"Devil! It's been a hot day. Thank God I can see our ships coming into the bay. Time to divide the spoils.",
"Split it like we agreed? Half for you and half for me?",
"I demand an increase in my share.",
"Why divide it? I'll take it all.",
"All right! I see you're a man of your word. We have seized gold to the amount of ",
" piastres. You're entitled to ",
" of that.",
"Not bad for a day's work.",
"Yes, while we still have time... What do you say we keep sailing together?",
"Sounds good to me.",
"I don't think that's such a good idea.",
"I'm glad you like my offer.",
"Welcome to the crew then, ",
". Now let's get back to our ships.",
"Well, I'd better get back to Isla Muelle. If you change your mind, I'll be there.",
"It's a deal.",
"Still considering my offer?",
"Yes, I haven't forgotten it.",
"No, I've made up my mind. Welcome to the crew.",
"Yoo-hoo! We're gonna do great things together! You and me! Just think of all the possibilities we have.",
"Yeah, yeah, but we've got a lot to do.",
"What?! No, it doesn't work like that! Either you take half or I'll have to kill you!",
"Come on, I was just kidding. Of course I'll take half.",
"For the last time, I don't want half!",
"Over my dead body!",
"I couldn't have said it better myself. En garde!",
"Am I hearing you, Captain?  What are your orders?",
"None. At ease.",
"Let's talk about our tactics during the boarding.",
"Yes, I'm listening.",
"I don't want you to come aboard with me.",
"I want you to come aboard with me.",
"Alright, Captain.",
"...",

};