string DLG_TEXT[411] = {
"...",
"...",
"What are your orders?",
"I don't want you to board with me.",
"I want you to board with me.",
"Are you ready to set sail, ",
"?",
"Yes, quite ready.",
"Hello, ",
"Blaze",
". I didn't expect to see you here.",
"Believe me, I'm just as surprised to see you. We can't seem to keep away from each other lately.",
"Ralph Fawn",
" is dead, and someone's going to pay!",
"I'm sorry hear that. ",
"Ralph Fawn",
" was a good man.",
"??? What are you doing here?",
"??? You're just full of surprises, aren't you?",
"Did you get the information you needed?",
"Well, I think we can trust this guy. But he won't tell me where ",
"Raoul Rheims",
" is hiding.",
"My god, ",
"! What took you so long?!",
"Relax. I told you I had other things to do.",
", ",
"Vincent Bethune",
" went ahead to the tavern. He said we should meet him there.",
"Looks like this guy's up to something.",
"Where is ",
"Vincent Bethune",
" going?",
"He said he had some business to take care of.",
"!!! Looks like some jokers are following us. Deal with them, then catch up with us. Go straight at the first intersection, then left at the next!",
"Will do. But remember: I need ",
"Raoul Rheims",
" alive!",
"...",
"What? ",
"Raoul Rheims",
" is dead?! What am I supposed to tell the governor?",
"?!",
"Yes, I'm glad to see you, too. How about a smile for someone who just saved your life?",
"We'd be smart to wait until dark. It'll be easier to sneak into town then.",
"Yeah. Good thinking.",
"What are you waiting for? We need to get into the residence before dawn!",
"We'll have to find another way in - a window, perhaps?",
"This might be a good time for us to split up.",
"Why? We make a good team.",
"We're in for a real fight. I need time to prepare my crew before we attack these cursed mines.",
"...",
"Men! I've decided to attack the gold mines at Oxbay. It's a dangerous proposition, and some of us may not live through this fight. But it's worth the risk!",
"Think of all the gold just waiting in there for a strong hand to take it! What is danger compared to that? Who's with me?",
"That rat Enrique stole off with my ship! Curse his scaly hide!",
"Now I've got to start from square one again. I'd best find a town and ask around for some work.",
"Well! At least that traitor wasn't lying when he said he got rid of those thugs...",
"Damned ",
"Enrique Forneris",
" escaped with my ship!",
"There is nothing I can do but find a town and ask around for some work.",
"Now I can pay a visit to the Spanish corsair who supposedly kidnapped the girl.",
"Go to the pirate's ship.",
"No, now's not the time for that.",
"Now I have to find that girl. I hope she's around here somewhere, otherwise I'll be in deep trouble.",
"...",
" He nearly killed me! I need to get out of here!",
"...",
"You don't understand! I can't show my face in the English colonies and the idol is on Greenford.\n Before ",
"Robert Christopher Silehard",
" has time to warn everyone about your 'betrayal', you need to sail over there and get the idol. Remember when you're looking for that statue, that the guy's name I gave it to was ",
"Giraldo Figuiera",
"Giraldo Figuiera",
".\nBut he's already dead, and I think it was because of that idol. You'll have to ask around at the tavern or the soldiers, and see what clues you can find.",
"And what'll you be doing? Looking for the last part of the legend?",
"Exactly. Hurry up - we don't have much time!",
"Don't worry about me. You just see to your end of the deal.",
"Oh, ",
", can't you be civil for one minute? Never mind - we'll meet in Oxbay, at that funny old man's place. Deal?",
"Aye-aye, my lovely captain.",
"You're right. But we'll have to go alone. A crowd will just attract unnecessary attention.",
"Agreed. Let's get going.",
"What happened? Who are these people?",
"You don't remember anything?",
"Don't push me, ",
", my head feels like it's going to burst. Why don't you explain what you're doing here?!",
"Take it easy! If anybody has a right to be mad, it's me. That dagger of yours didn't exactly tickle!",
"Serves you right! You work for the English governor and he's after me. Let's settle this matter once and for all! Get your sword out, you bastard.",
"Don't be ridiculous, ",
", I'm not hunting you. I didn't even know ",
"Robert Christopher Silehard",
" wanted you dead!",
"You're lying! And it's not the first time, ",
"! You said yourself you'd do anything for gold, didn't you?!",
"Oh, for crying out loud, ",
", I was just playing a part! You were so sure I was a scoundrel, I didn't want to disappoint you!",
"What are you talking about? I've always thought you were an honest man!",
"Oh, sure! Look, we've known each other for a long time, and we've spent most of it in competition with each other. But that doesn't mean I'm out for your blood!\nOr do you just have a problem with me because I'm a man?",
"So what if I do? Men are dirty beasts, and you're no exception!",
"Really? Have I hurt you in any way? Seems to me I'm regularly saving your sorry hide!",
"That's debatable. But the fact remains that you're working for a man who wants nothing more than to see me dead!",
"Correction. I worked for him, ",
". I'm...retired now, although ",
"Robert Christopher Silehard",
" doesn't know it yet.",
"Why? Didn't he pay you enough?",
"Believe it or not, gold has nothing to do with it. There's not enough coin in the world to keep me running errands for a man like him.",
"Then why are you here? If you're a free man, then go!",
"Fine. I can see you haven't changed a bit. I'm as good as gone, and you'll go, too, if you know what's good for you. These corpses are going to attract a load of trouble before they attract the first fly.",
"!!!",
"What is it now?",
"...",
"Did you have something else to say, or can I go?",
"... Thanks, ",
", I'd be dead now if not for you.",
"Forget it. Can I go now?",
"Wait, ",
"! Where are you going from here?",
"I'm going to pose some questions to a certain crooked governor.",
"Just wait a minute, will you? You can't go there alone. That's suicide! If ",
"Robert Christopher Silehard",
" suspects anything at all, he'll kill you just to be safe!",
"Thanks for the warning. I'll take my chances.",
"Then I'm going with you!",
"What for? I can handle myself.",
"First of all, I've got my own questions for the governor. And second... second...",
"What?",
"I know a place on Redmond where we can safely land, with no one to trouble us.",
"All right, fine. We're partners. Temporarily.",
"Agreed. One thing, though: if you set me up, ",
", I swear I'll kill you.",
"Deal.",
"So you're working for that English dog?",
"Exactly, darling. You could say I'm his right hand.",
"What business? He never told me anything about it!",
"How should I know? We'd better talk to our fugitive.",
"I can't help thinking you're hiding something from me, ",
".",
"Please, ",
" will you just trust me for once?",
"All right. We'll talk about it later. ",
"Raoul Rheims",
" is here, right?",
"Yes, he's sitting at that table there. Let's buy him a drink and have a little chat.",
"Oh, relax, ",
"! He just went to find out if ",
"Raoul Rheims",
" still lives here. That's all.",
"Right, let's head for the tavern.",
"Sure, but you didn't say you'd be missing for several days!",
"Is it possible you were worried about me, ",
"Danielle",
"?",
"Yes, it's possible. In your wildest dreams!",
"Nice. Well, I'm here now. Where's ",
"Vincent Bethune",
"?",
"He's on my ship, fighting a courageous battle with crushing boredom.",
"Look, I'm sorry for the delay, all right? Where do we go now?",
"To Douwesen. ",
"Vincent Bethune",
" says he lives there.",
"Great. Let's not waste another minute.",
"Wait. Isn't your crew a bit too big?",
"Maybe you're right - I'll see who I can leave ashore.",
"Put to sea, and I'll join up with you.",
"All right.",
"So you were going to find him by yourself? That doesn't work for me, ",
"!",
"Relax - that was never the plan. Look, let's go find him together. You'll talk to him, learn what you need, and then I'll take him to the man who wants to see him.",
"Fair enough. But I've got some business to take care of first. What say we meet here in a few days?",
"Fine. That'll give me time to make a report to my employer.",
"I'm not in the mood for your jokes right now, ",
" - I've had a rough day.",
"My day wasn't any better, believe me. Who's this dandy you're with? Should I be worried?",
"Don't be a pig, ",
"! He's just... a friend of mine. ",
"Vincent Bethune",
". He's helping me look for a captain by the name of ",
"Raoul Rheims",
"Raoul Rheims",
".",
"You're kidding! I'm looking for him too - although, to be honest, I seem to have lost his trail.",
"What do you want with him?",
"Money, sweetheart. I was promised a hefty sum to bring him in.",
"Watch it with that 'sweetheart' stuff, ",
"! I've always suspected you were just another money-grubbing scoundrel!",
"I never pretended to be anything else, ",
". So, you know where ",
"Raoul Rheims",
" is hiding?",
"No, I don't. But ",
"Vincent Bethune",
" claims he knows where the guy has settled.",
"This is almost too convenient. You just happen to run into the one person who knows where to find the man you're looking for?",
"Don't be so suspicious, ",
". Not everyone is a scoundrel like you.",
"What's that supposed to mean, ",
"? I'm just trying to see all the angles. How does ",
"Vincent Bethune",
" know where ",
"Raoul Rheims",
" is hiding?",
"Why don't you ask him yourself?",
"I think I'll do just that.",
"I don't see what's so funny, ",
"Blaze",
". Go bother someone else if you've got nothing better to do.",
"Still hiding your deep and abiding love for me, are you? Fair enough. If you'd rather be alone, that's how I'll leave you.",
"Save your compassion for yourself, ",
"! I don't need it.",
"Whatever you say. But why do you think those soldiers attacked us all of a sudden? I don't recall having a quarrel with the English. How about you?",
"That's none of your business! At any rate, I'm not going near another English flag for a while. I'm clearing out of this town, and I'd advise you to do the same.",
"Wait!",
"?! How did you get here?",
"? How did you end up here?",
"I came here looking for you! I was afraid you were already feeding the sharks!",
"You were actually worried about me? I'm touched.",
"You?! I was worried about the idol! I'd have had a hard time getting my hands on it if it was at the bottom of the sea with your ship.",
"The idol's safe with me. But speaking of ships, where's yours?",
"I had to trade it for that tablet. But it's going to be worth it when I find the treasure! It could buy a hundred first-class ships!",
"I hope you're right. Where's this overpriced slab of clay now?",
"The tablet...? Well... It weighed like a cannonball so I wrote it all down on paper. . Without the ship, it wasn't easy to carry it around..",
"You're not making any sense, ",
", why do I get the feeling you're hiding something from me?",
"Even so, you'll have to make do with what I've told you.. Here's a copy of that damned native legend. Any other questions?",
"Just one. What do we do next?",
"I hope there's a cabin on your ship for me! Otherwise you'll have to move to the quarters.",
"You'll have your cabin. Now come and join us, I've got a lot to tell you.",
"Later. When you're done having fun, go upstairs. There we'll continue this conversation... Try not to get drunk!.",
"They don't even let you have a good time! What a life!",
"My ship was stolen, and the tablet along with it. Luckily it occurred to me to copy all of the tablet's text onto paper.",
"Don't blame yourself, ",
". Worse things happen at sea, you know.",
"Spare me the cliches, ",
"! I'm not blaming myself. But you won't have to put up with me on your ship for too long! Soon I'll have a ship again, and then I'll catch that rat and hang his giblets out dry on the ship's rail!",
"Listen to you! You sound like a pirate!",
"I'm a corsair! I swear as I please!. You want fancy manners, go back to Silehard's service!",
"No, thank you. I'm not such an idiot as to give up the treasure!.",
"Then let's work out our next move. We need to find someone who can translate this ancient gibberish! If we don't want to end up like Rheims, we'll need to read the entire text.",
"True enough. You know, if I remember correctly, ",
"Researcher",
" has been known to boast of his knowledge of ancient languages...",
"That's right! Let's pay him a visit.",
"To Greenford, then! I'll be waiting for you aboard the ship tomorrow morning.",
"What took you so long? Are we ready to sail?",
"Of course. The ship's in perfect shape.",
"Let's get under way, then!",
"Don't forget who the captain is here.",
"Let's get under way, then!",
"Don't forget who the captain is here.",
"It looks like we'll have to free ",
"Researcher",
" from Greenford's prison.",
"Yes. Or find someone else who can read the legend.",
"I don't think we'll find another man with his education in a million years. Not on these islands!",
"So what do you suggest? We just sneak into town and storm the prison?",
"Why sneak into town when we can capture it?",
"Capture it?! Have you lost your mind?",
"Not at all. You hit the fort from the sea, and I'll take my crew through the jungle and attack from land. They'll never know what hit them!",
"I'm sure it sounds easy to you. You don't have to attack the fort!",
"Would you rather slog through a jungle teeming with poisonous vermin? No problem - I'll trade with you in a heartbeat!",
"No, no. That wouldn't be...fair to you. I'll stick with the sea.",
"I thought you'd see it my way. We'll need some time to plan the assault - it won't be a cakewalk. When we're ready, you can put me and my crew ashore at the lighthouse.",
"Right. Let's get back to the ship.",
"Why waste time? Let's attack now, before we have a chance to change our minds!",
"Are you sure? We'll be fighting soldiers this time around, not some fat trader's crew!",
"We have plenty of manpower to capture the colony!",
"Well, maybe we should take some time to prepare.",
"I'd just about give my sword arm to see the governor's face when he hears about this!",
"Forward!",
"Are we going back to the ship, ",
"? Or have you decided to take a stroll?",
"Yes, of course we're going back to the ship.",
"This is always the hardest part - when the planning's been done and you're just waiting for the right time to move.",
"I can think of a few ways to pass the time...but never mind that.",
"Let's put some fear into the hearts of these landlubbers!",
"Indeed! I'll make the governor regret using me!",
"Wait! We've got to finish our preparations first.",
"Please, ",
"! Hurry up!",
"Don't push me! I'm not going to rush into a battle like this.",
"When the smoke clears, we'll meet at the center of Greenford! And don't be distracted by plunder - we won't need this town's rubbish when we find the treasure!",
"And don't you let the thrill of the fight distract you from business!",
"Don't worry about me! ",
" Just try to stay alive, all right?",
"It'll take more than this town to kill me! Good luck, ",
".",
"That was some battle! Are you all right?",
"Of course! I didn't plan on dying today!",
"Well, Death doesn't generally make an appointment, you know!",
"Right. Let's go free ",
"Researcher",
".",
", we can talk later. We need to free the old man first.",
"Agreed.",
"So how long is this going to take?",
"Researcher",
" said he'd need several days to translate the text.",
"It's been a week already! I'm getting bored.",
"Just keep picturing those piles and piles of gold. That'll cure your boredom.",
"I can't wait to set sail! Why can't he do his translation on the way to the temple?",
"I don't know...I hadn't thought about that.",
"Yeah, I guess a pirate doesn't have much use for brains. Maybe you don't have much use for gold, either, ",
"?",
"What?",
"I'm asking what you're going to do with your share of treasure. Entertain me.",
"I don't know. I'll buy an English island, I suppose, and make my own rules. Or maybe I'll become an English peer. That could have its rewards. And you?",
"I'm not telling. It's my secret.",
"All right. Be that way.",
"Are you going to take on the regular fleet?",
"No - I'm going to crush it!",
"I'll command the fort! Just try to keep the fight in range of the cannon.",
"And you just watch who you're shooting at!",
"We won! Now that was a battle! Ha! Together we could have taken the whole archipelago! Or even the entire Caribbean!",
"But it's better if we just visit ",
"Researcher",
".",
"Damn it, ",
"! Shame on you for crushing a sweet girl's dreams with your bloody logic!",
"All right. If, after we find the treasure, you still wish to conquer the Caribbean, I'll be with you.",
"I hope that scholar had enough time to examine those scribbles. We may not be able to repel a second attack.",
"I have serious doubts that the Governor still has any warships left.",
", the temple is most likely located in the interior of the island. We'll have to take a walk.",
"I think we'd better leave the crew on the ship. We'll see the temple with our own eyes first.",
"I can't believe we found it! A few more hours and we'll have all the treasures of the ancient temple in our hands!",
"Maybe there isn't any treasure.",
"Don't say that! We couldn't have come so far for nothing, it must be there!",
"We'll see.",
"There are three passages here, and any one could be the right one. Where should we go?",
"I don't know. This could be the trap ",
"Researcher",
" was talking about?",
"Then we should split up. We'll cover more ground that way. I'll take the left passage for myself, and we'll see who finds the treasure first!",
"Hey, wait...",
"Looks like we can go to Khael Rhoa now!",
"Something tells me it's not gonna be that easy.",
"Maybe we should go ahead and search the temple while he's reading those squiggles.",
"Not without some idea of where we're going! The devil himself could get lost in that maze!",
"Have it your way. I'll go alone. I see the first piece of my share of the loot already!",
"What?",
"That's got to be the alcove ",
"Researcher",
" was talking about. But where's the treasure?",
"I don't know. Even if we stripped all the gold from the walls it wouldn't amount to much...",
"We can't waste much more time looking, ",
". They'll capture the town!",
"I just want to be sure you don't sink me, too, after we take care of the English fleet.",
"Now, that really hurts, ",
".",
"Kidding! I'm just kidding. Good luck!",
"Good lord! What was that?",
"I have no idea!",
"Three thousand devils, ",
"! No one could survive that! My treasure! Could we just try to get part of it? Just a wee bit?",
"Hey, I'm sure it's not the only treasure in the world!",
"Who cares! It's still a loss!",
"I'm not sure you care as much about the gold as you pretend to...",
"I shouldn't go back there. I need to get off Redmond fast!",
"Poor ",
"Ralph Fawn",
"! I swear, the governor will pay for his death! But why would he give such an order? Did he think ",
"Brendan Applin",
" told me more than I need to know? I've got to find out what's going on!",
"Brendan Applin",
" mumbled something about treasure. And treasure is a sure cure for boredom. I guess I'll pay a visit to Quebradas Costillas. ",
"Brendan Applin",
" also mentioned someone named ",
"Raoul Rheims",
"... Maybe I should seek him out.",
"Hm... This seems to be some kind of journal. And the author is probably this ",
"Raoul Rheims",
", the man I'm looking for. Blast! Most of the pages were destroyed by water. Only the last few are readable: '...repairs will soon be done,\nand I'll have to go to Redmond  to inform His Grace of our failure... The key must lie in those parts of the legend I couldn't read. I shall seek out all traces of this myth, and next time I WILL find the temple...'\nHm. And the next entry: 'God help me, I was shot today! The rat got away, but I think I recognized him. I'm sure I've met him at the governor's residence. Can it be that ",
"Robert Christopher Silehard",
" has ordered my death? It seems I'll have to lay low for while.\n",
"Camilo Machado",
" won't deny me refuge. Then I can try to find out what's going on... I hate to leave my navigator, ",
"Giraldo Figuiera",
" here, but he's caught malaria and wouldn't survive the trip. I hope he's smart enough to hold his tongue.'",
"(Read more.)",
"(Stop reading.)",
"God, not Quebradas Costillas again! But this is the only lead I have.",
"'We set sail today. The sky is clear so far. I hope it stays that way until we reach Conceicao. The events of the past few days have drained my spirit. I don't know what to think anymore. I don't know what to do. Maybe I shouldn't have involved myself in this...'\nAha - this entry was made several days later: 'At last I feel safe. ",
"Camilo Machado",
" greeted me with open arms and promised me protection within these walls. It's bought me time to think.'\nAnd here's the last entry: 'I got an idea today: Instead of wasting time here, I should be looking for the source of the legend that led me to the ancient temple. I've bought a small house from one of the locals; it will serve me as a base. I'll set out tomorrow, leaving everything I don't need here.'",
"...",
"...",
"Thank God! I seem to be in time. When you disappeared I just lost my head from worrying!",
"Well, I'm flattered... Didn't even expect this from you, but what are you doing here?!",
"Nathaniel?! What are you doing here?! Although, knowing you, I shouldn't be surprised!",
"And what are you doing here, dearie?",
"Suit yourself, but I've got things to do, you know. Goodbye.",
"Wait! Can you tell me if the merchant, Arnaud Matton, is in town?",
"Me?! Well, when you disappeared, I made some enquiries... Anyway, I had to take over the town..",
"Take over the town?! Are you crazy?!",
"What?! That's your way of saying thank you? Fine!, stay in your cell!",
"I'm sorry, I didn't mean to sound like that. I just wasn't expect you to do this for me...",
"I wasn't expecting neither myself... It's just... Forget it, let's get out of here.",
"That's right. Besides, I've still got some business with the local merchant.",
"You mean Arnaud Matton? He's out of town. I think he went into the jungle and there's no use looking for him.",
"Oh, the devil. All right, open the cell.",
"All right, Captain..",
"...",
"Me? Well... I just took over this colony and thought I'd look around to see who's in here.",
"Well... as you can see, it's me. ",
"Did you rob someone again",
"Something like that... But are you gonna let me out or not?",
"Oh, for God's sake!",
"Thanks for that.",
"Nah. I charged him a ransom and let him go. I think he already left town and is hiding somewhere in the jungle.",
"Well, thank you.",

};