string DLG_TEXT[99] = {
"I don't believe I've seen you here before, lad.",
"That's because it's my first time in town. My name is ",
".",
"So what? It's the first time I've seen your rascal face, but I'm not commenting on it in any way, am I?",
"I'm ",
", the owner of this tavern.",
"Glad to meet you, ",
". I was wondering if I could use some of your services.",
"Relax, I'm not looking to give you any trouble. My name is ",
", and I'm here to talk business with you.",
"I'm listening, what do you need?",
"I'm looking for a crew. Maybe you can tell me who's looking for a ship.",
"My last voyage left me short on crewmen. Point me to suitable cannon fodder here in your tavern, and I'll be on my way.",
"Please, answer me some questions.",
"Do you have a cot I don't have to share with a thousand insects?",
"I need a clean room with a bed. Emphasis on clean.",
"Sorry, I don't have time to chat. So long.",
"That depends on what you mean, ",
". But go ahead.",
"I'm looking for a man named ",
"Raoul Rheims",
", I know that he arrived recently in this city.",
"I'm looking for a man named ",
"Raoul Rheims",
"Raoul Rheims",
". Do you know if he's been on this island?",
"I'm looking for  ",
"Ferro Cerezo",
"Ferro Cerezo",
", do you have any idea where he might be?",
"I'm looking for a certain man that came to the island not long ago. He's Italian, an older man. Has anyone like that showed up here?",
"I'm interested in someone named Artois Voysey. He is a tall young man with dark hair. Has he showed up around here?",
"I need some work. Is there any bigwig on the island who's afraid to sail alone?",
"I have heard there's a lot of pirates in these waters. They say as many as five ships! What's the governor is waiting for?",
"Let's talk about something else.",
"Yes, I've seen him, but I don't know if the news are gonna like you\nThe thing is, the guy showed up here and sat down at a table with some scoundrel. Within five minutes later, the door swings open and two bastards in black masks appeared\nThey took Artois with them, and heavily wounded his friend. He's in one of the rooms upstairs right now.",
"Thousand curses! I need to see him! Maybe he knows who these masked troublemakers are.",
"Now, let me think.... Oh, but of course! ",
"Vito Leone",
" quite matches your description. He came in a week ago, and rented a room from me. He said someone would come looking for him, and he asked me to tell you that he's waiting for you at the church.",
"Thanks!",
"The man at the table near the window goes by that very name, if I'm not mistaken.",
"Thanks. I'll check him out.",
"Keep it down! The walls have ears, my friend.",
"So what? I've got no secrets.",
"Be quiet! They say this man is protected by ",
"Camilo Machado",
"Camilo Machado",
" , the chief of the smugglers. - I wouldn't want to attract the attention of such a powerful man.",
"Yes, ",
"Raoul Rheims",
" is on the island. You'll find him with ",
"Camilo Machado",
"? How can I find him?",
"That's the first I've heard of that. Perhaps you're mistaken.",
"I know for certain he arrived here several days ago. He was to meet with ",
"Camilo Machado",
"Camilo Machado",
".",
"Quiet! If you value your life, you won't say that name out loud again. Look! Did you see that man who just left the tavern? Get away! Go now, or you'll bring the sky down on my head!",
"Pull yourself together, man! You're quaking in your boots...and you don't even know anything useful, do you? Bah. Goodbye!",
"Relax! I can see you're not going to be of any use to me. Goodbye!",
"Sorry, but it's very late. Everyone's found a place to spend the night by now. Come back in the morning if you like. Or you can spend a night here in the tavern.",
"Maybe I will. Do you have a room?",
"I might just do that. But for now, I've got some more questions.",
"As it happens, I do have a vacancy. How long did you plan to stay?",
"Until morning.",
"Just until night falls.",
"It'll cost you 5 gold.",
"Fine. Here's your money.",
"Alas, it looks like a bed is beyond my reach at the moment. I'll just sleep in the tavern-hall.",
"You want how much?! Do I get a fruit basket with that? Thanks, but I'll just sleep in the tavern-hall.",
"I'll consider it. Meanwhile, I need some more information.",
"It'll cost you 5 gold.",
"Here's your money.",
"Sadly, that's more than I care to spend. I'll sleep in the tavern-hall.",
"What's that for, a king-size room? No, thanks, I'll sleep in the tavern hall.",
"I'll think about it.",
"This is a respectable establishment! Stop at once, or I'll call for the guards!",
"All right, all right. I'm leaving!",
"If there is such a person, he might prefer to avoid attracting attention with so many consorts - as I'd expect you to know.",
"Yes, I forgot. All right, I'll come back later, when I've got fewer ships, ha-ha.",
"I don't want to help you, with all the harm you've done to my country.",
"What a patriot you are. Alright, farewell.",
"Your hands are covered in blood. Do you seriously think that somebody will sail in your company?",
"You are right, everybody is afraid of me! Ha-ha!",
"You came just in time. One merchant here was searching to sail in company with just the right companions. You'd better talk to him. Here he is, coming into the tavern.",
"I'll do that.",
"No, there is nobody for the moment. Maybe next time.",
"Okay, well, that's a deal breaker.",
"Don't you touch him! He had the goodness to accept the help of one captain who came up with the whole pirate idea, thank God. Ha-ha!",
"Wait, what do you mean?",
"What I mean is that these are our ships, sailing under a pirate flag\nHis indulgence got pretty fed up with the smugglers establishing themselves on our island, and decided to eradicate them to the ground.",
"Hmm... And who was the man who came to his aid and suggested such a brilliant idea?",
"I don't know his name or what he looks like, but I hear he used to be a smuggler himself...",
"Ha! So there's a traitor in the midst of these bastards?!",
"Aha! Imagine that! And I like your political views mate, that Machado was keeping everyone here in fear\nEven you, I remember, had some trouble with him, when you were looking for your man.",
"That's right! Imagine - they took my friend for money he didn't pay, to settle up with them. So I helped him out.",
"You're a hell of a guy! Here's some rum on the house.",

};