string DLG_TEXT[55] = {
"Don't bother me while I'm working!.",
"...",
"Any orders, cap?",
"No, not yet.",
"A new prisoner, he-he!",
"Why are you so happy about it?",
"Here is your weapon. Now, to get out of here, you have to kill all the soldiers on guard. There are two or three of them.",
"Thank you, I owe you one. I'll meet you at the port.",
"Thanks for the sword. Unfortunately, I'm a vengeful person. Do you remember you swore that I'd be walking on crutches till the end of my days? Well, I am afraid you'll have to.",
"What do you need?",
"You said you used to serve as a gunner. I'd like to hire you.",
"I am glad you managed to free yourself, cap. Is our deal still on the table?",
"Yes, how much do you want for your services?",
"No, I don't need your services.",
"Me? Are you kidding, captain?",
"Do I look like I'm kidding? How much do you want for your services?",
"Just 2000 gold per month, sir, and I am completely at your service!",
"Good, consider yourself hired. Welcome to our crew.",
"I don't think that your services are worth that much money. Goodbye.",
"Why? A new prisoner requires money by the governor for his keep, from which I'll get my share, he-he.",
"How did you end up like this?",
"The new prisoner wants to talk? Well, let's talk then\nBut you'll soon lose that desire and will just be sitting on your bunk, staring at the ceiling\nI know you, I've seen many like you in my time.",
"You haven't answered my question yet.",
"It's a long story, but hell, you've got time, he-he, so why don't?",
"You're right, I've got plenty of time, so tell me your story",
"Don't interrupt me or I'll interrupt you, he-he. You'll spend the rest of your life walking on crutches.",
"Be careful with what you say! I may be in this cell, but I'm still a captain, and I'm not going to be insulted by a wretched jailer!",
"A wretched jailer? I was once the best gunner in this damned archipelago!",
"You think I believe that? Who would dismiss a first-class gunner?",
"I didn't believe it would happen to me either, and it's the damned rum's fault\nThey kicked me out, without even paying me for the last six months of work.",
"Gunner, help me get out of here, and I'll hire as an officer on my ship. You'll be forbidden to drink while we sail, but on land you can drink to your heart's content!",
"Out to sea again? Damn it, don't torment me, cap!",
"I am not kidding. Just open the door, give my weapon back, and I'll get out of here and meet you at the port at my ship '",
"'.",
"No, that won't do! There, risking your neck. You stay here, mate, and I'll go about my business",
"Wait!",
"It's a deal, captain...but you'd better not fool me!",
"Don't worry, I keep my word.",
"...",
"Attwood, drunk again...",
"Captain, I thought we had an agreement - what I do ashore is my business. I'm not getting drunk on the ship, so you can't complain.",
"And you got yourself in a fight again.",
"It's not just a fight, cap! It's a matter of honor. That guy called me a son of a jackal and a land-rat.",
"No arguing! Get on the ship!",
"A matter of honor? No one dares to insult my officers. Defend yourselves, scum.",
"Well, Cap, I thought better of you.",
"...",
"What are your orders, captain?",
"None. At ease.",
"Let's talk about our tactics during the boarding.",
"Yes, I'm listening.",
"I don't want you to come aboard with me.",
"I want you to come aboard with me.",
"Alright, Captain.",
"...",

};