string DLG_TEXT[161] = {
"Welcome, ",
". At Everard Gordon's Tavern you will find everything that can please a sailor's heart!",
"Thanks for your welcome. I'm ",
".",
"Welcome, dear ",
". Glad to see you back in our town.",
"! What can I get you?",
"Why, hello, ",
".",
"Can you help me to hire crew?",
"I'd like to talk to you.",
"I'd like to stay here for a while.",
"I need a clean room, with a bed and no bedbugs.",
"I'll be on my way now, ",
". Farewell.",
"What can I get you, dear ",
"?",
"I'd like to hire some sea dogs for my crew.",
", we need to talk.",
"I'd like to stay here for a while.",
"Is there is a free bed in this dump?",
"I'll be seeing you, ",
". Farewell.",
"As it happens, I do have some rooms. How long did you plan to stay?",
"Until morning.",
"Until night.",
"It will cost you 5 gold pieces.",
"All right. Here's your money.",
"That's more than I can spend at the moment. I'll pass the night in the common room.",
"Are you renting the King's chambers? No, at that price I'd rather stay in the common room.",
"All right, I'll think about it.",
"It'll cost you 5 gold pieces.",
"All right. Here's your money.",
"That's more than I can spend at the moment. I'll pass the night in the common room.",
"Are you renting the King's chamber? No, at that price I'd rather stay in the common room.",
"Not now. Let's talk about something else.",
"What do you want to talk about, Captain ",
"?",
"I'd like to know how the locals have received the French...",
"Gossip, rumours, anything you've heard lately.",
"There's some business I'd like to discuss with you...",
"Business? Now we're talking!",
"We don't have anything to talk about, though.",
"Have you seen a man around here by the name of ",
"Counterspy",
"?",
"Do you recall the French officer I spoke to last time I was here?",
"It seems like the French squadron has receive a new reinforcement recently.",
"Is your boat ready, ",
"?",
"I need information about a certain man. He wears red robe all the time, and calls himself the 'Teacher'.",
"I'd need a job. Do you know if there's any bigwigs on the island who are afraid to sail alone?",
"Even if there were, they prefer to sail as part of a smaller squadron. You know that.",
"All right, I'll come back later, when I have fewer ships, ha-ha.",
"I don't want to help you, mate. You've caused too much trouble for my country.",
"Quite the patriot, aren't you? Well, goodbye then.", 
"You got blood on your hands. Do you really think anyone would like to sail with you?",
"You are right, everyone's afraid of me! Ha-ha!",
"You came just in time, lad. There's a merchant here just looking for the right company, and here he is, see he's entered the tavern? Talk to him.",
"I will. Thanks.",
"There is nobody here at the moment. Maybe next time.",
"All right, no deal.",
"Yeah, I remember that one. The fool was arrested in Greenford. They say he was trying to start a riot. If you want to find him, go straight to Greenford Prison.",
"Thanks. I appreciate your help.",
"Curious. I'm looking for a crew.",
"I'd like to talk to you.",
"I'll be seeing you, ",
". Farewell.",
"As you wish, captain. Whatever you say.",
"Thanks. Meanwhile, can you help me to hire crew?",
"I'd like a word with you.",
"I'll see you next time, ",
". Farewell.",
"Look around you, captain! Who would you hire? Every able-bodied man has been taken by the French to work on their ships.",
"I see. Perhaps you can help me with something else, then.",
"I'll be going now, ",
". Good day.",
"The French? How could we accept those bastards! They looted half the town, when they swore they wouldn't hurt anyone\nPoor ",
"Mildred Backer",
" had to flee the city to avoid being... ahem.... And her father was slaughtered by the soldiers when he resisted!",
"Those bastards! Tell me, ",
", would you like to see the flag of England over Oxbay again?",
"Pure horror, captain! The French took the fort by surprise and captured the town with almost no losses from their side\nThen, they declared that we were now under the protection of the French Crown. Everything was going to be all right\nAnd soon after that, the looting began! The devil! Replenish their supplies at our expense.",
"It seems, dear tavern-keeper, that French citizenship it's not to your liking?",
"Oh, I pray to God to get these invaders out of here as soon as possible\nThey drink gallons of ale and rum every day, and I'm afraid to even mention about the payment!",
"The fact is, I'm here on behalf of Sir Robert Silehard.",
"Redmond's governor? Is his lordship already aware of the attack? So why won't he take any action to retake the colony?!",
"For now, I'm gathering information on the French further plans.",
"You're not a shy one, sir! Well, I'm ready to help you!",
"What going on in the city?",
"Nothing much... The population is hiding, either in their houses or out in the jungle\nEven though the French have set up a post at the city gates, every day several citizens manage to escape into the jungle\nThe French get drunk and hit on women, even the elderly. Also, they need men. The squadron command is hiring crew for their squadron for very good money\nBy the way, ",
", this could be a very good opportunity to send a spy to the French.",
"Perhaps you've heard something about what the French are up to?",
"Well... I heard two drunken officers talking about how they were waiting for a ship with supplies. But they've got plenty of food here!\nOh, I got distracted... So, when that ship arrives, the squadron will put to sea.",
"That information is already worth something!",
"I'll do my best, sir! If I hear anything else, I'll let you know right away!\nThese pigs are so full of it, they can't wait to tell you more.",
"You say, when they're full of it, they're ready to tell everything?",
"That's right! sir ",
", you should hear what's going on here past midnight!",
"I've got a plan.",
"A plan? And you're going to share it with me!",
"The plan is very simple. That guy over there in the French uniform - do you know him?",
"Yes, that's the officer from the French frigate. He visits me regularly.",
"Are you prepared to spend a little money to liberate Oxbay?",
"Gold? Sir ",
", would you mind explaining your plan to me?",
"It's very simple, I intend to get this fellow drunk, and then get the details out of him.",
"But, sir ",
", who's going to pay for the drinks? I mean, I'm willing to donate for Oxbay's release, but that kind of money?!\nI have a pretty good an idea of how much two sea wolves can drink!",
"Look, Governor Silehard will reward you for your spending!",
"Damn it! How much do you want?",
"Do you really think he'll reward me, sir? Well then, let's get on with your plan!",
"Splendid! Just in time to serve the drinks!",
"Oh, no, sir! It remains to be seen whether the governor will reward me. You must understand, I won't give you drinks without money",
"You're kidding, innkeeper! Do you want me to rip your belly open?",
"Damn it! How much do you want?",
"Let me see... ",
" gold pieces. And not a coin less! I know it's expensive, but this is wartime!",
"There! A thousand devils! And woe to you if you serve diluted rum!",
"I have no money, Everard.",
"I wouldn't be angry if I were you, sir! Look around, there's French patrols everywhere. Threaten me, and I'll turn you in!",
"Scoundrel! How much do you want?",
"Don't worry, sir ",
", let's get on with your plan!",
"All right.",
"You don't have any money at all? No way!... Oh, alright!... proceed with your plan. I hope the Governor will make it up to me!",
"Thank you, Everard!",
"Not to your taste?! Blow them all up, scoundrels! They show up at my tavern every day and drink gallons of ale and rum, and I'm afraid to even mention payment!",
"And if I say...",
"No problem. Just 10 gold pieces and the room is yours.You can get a room for just 10 gold pieces.",
"No, that's too expensive.",
"All right. Here's your money.",
"Hardouin Beauvallet",
"Hardouin Beauvallet",
"? Of course. He's a regular at my tavern. Every night he comes here and drinks a couple of bottles of my best wine. Naturally, for free!",
"Then I'll wait for him here.",
"Yes, indeed. A French battleship came into port the other day. If it comes to a naval battle, it will cause a lot of bloodshed among our ranks.",
"Then we must destroy this ship before any battle occurs.",
"Hmm... But you can't get there from the sea - the port is well guarded. Unless\nThe ship's entire crew is ashore - on leave. Only the watchmen are left on board.",
"What's your point?",
"I think a lone boat could slip into the ship, at night. And if there are a few brave men who dare to do so, I have a boat.",
"Get your boat ready, ",
"!",
"Bring your boat to port at night. We'll be waiting.",
"All right, but there's still a long way until nightfall. Will you stay at my tavern? I won't charge you.",
"I guess it's better to be here that wandering around in the street.",
"Silence, ",
"! The boat is ready. Did you find volunteers?",
"Yes. Tonight, the boat must be in the port tonight.",
"I'll be there...",
"Let's wait for dark, then.",
"Let me offer you a room on the house.",
"Thank you, ",
".",
"Quiet! He's on the second floor, wearing a French uniform, but it's just a cover.",
"Thank you.",
"Come on, everyone's at home now - it's night. I'd wait till morning if I were you. Maybe you'd like to get a room?",
"Do you have any rooms available?",
"No, let's talk about other things.",
"Dear people, please stop this outrage in my tavern or I'll call the guards!",
"All right, all right, I'm leaving now.",

};
