string DLG_TEXT[144] = {      
"Good to see you, ",
". My name is ",
", and I am entirely at your service.",
"And my name is ",
", and I'm the captain of the ship.",
"Good to see you again, ",
".",
"It's you again? I was hoping I'd never see you here anymore.",
"Good health to you too, ",
".",
"Don't worry, merchant.",
"Would you like to inspect my wares?",
"That'd be nice. Show me what you got.",
"Later, I've got something to talk about with you at the moment.",
"Some other time, when I come here again.",
"Do you have merchandise to sell, or do you just need some personal items, captain?",
"I'd like to sell the cargo I've brought.",
"I'd like to buy a few things for myself.",
"Not at all. Have a nice day.",
"I'm listening, what do you want to talk about?",
"I'm listening.",
"I've been instructed to deliver your cargo.",
"Don't you need a captain, monsieur? I have a fine ship, and I can deliver any cargo you desire.",
"Hush... be quiet. I come on behalf of Machado.",
"Oh, it's you again! Are you trying to get me into more trouble?",
"Just pay for the sandal I delivered to you, and you won't see me again.",
"I want to talk about the shipment of sandalwood I delivered to you not long ago, and the money you had to pay for it...",
"Ah?! What? It's y-you?!",
"You didn't waste time, you bastard! ",
"Is that you again?!",
"Remember me? Good! Now let's talk very seriously. So serious that I recommend you lock up the store, so no one will disturb us.",
"How can I help you, monsieur?",
"I need to talk to you. So lock the store to avoid any sort of misunderstanding - it's going to be a long conversation.",
"Ah?! What? It's y-you?!",
"Me. And I have an offer you won't be able to refuse.",
"You've ruined me! Now they're going to confiscate my store and send me to prison!",
"If you hand over Machado's papers, I'll put in a good word for you.",
"Well, there's no need to talk now.",
"No, it's not. At least not as long you keep sinking Portuguese ships.",
"In that case, good-bye.",
"Sorry, but I don't have anything for you right now",
"All right, I'll come back some time later, then.",
"I'm sorry, but your ship isn't big enough to carry out the errand I want to give you.",
"Well, I'll come back later, then.",
"Oh! I was just about to ask you for a favor of my own. The thing is, I need to deliver a shipment to ",
", as soon as possible. If you can do it in a month, you'll receive when you get there ",
" piastres, as remuneration. Agreed?",
"Agreed.",
"I'm sory, but that's not good enough for me.",
"I already told you, I don't have anything for you right now.",
"Oh, I'm sorry.",
"You're a little late in the game, won't you think? I've already got everything I wanted. Good-bye",
"Farewell.",
"Oh! I've been waiting for this for a long time. Here's your reward, lad.",
"You're welcome.",
"I don't need of your services at the moment.",
"That's too bad. Let's talk about something else, then.",
"Oh! So you have brought the shipment of sandal I've been waiting for?",
"Exactly. Perhaps your men can take care of the unloading?",
"Of course! In the meantime, please rest in the room upstairs.",
"Not a bad suggestion, I think I'll take it.",
"It's a done deal. I already imagine the profit I'll get by selling this, he-he. Oh!... who's there?!",
"What the...?!",
"It's just my customer, honourable officer... (whispering) - Get out of here and don't you dare fight them. This is a test, come see me in a couple of hours, and we'll sort this out.",
"Oh, I can see I'm in your way... Well, I must be going now...",
"What sandal, what money?! What are you talking about!",
"Did you deny the fact that I delivered you this cargo?",
"No, not at all! But I don't have the shipment! It's been confiscated. I've had to pay a gigantic fine, and I'm on the verge of bankruptcy!",
"That's interesting. But Machado, for some reason, believes that all of this it's your doing, so he has asked me to look into it.",
"God forbid! Do you really think I want as an enemy, a man as powerful as Machado?!",
"I don't care what you want, merchant, I want the money you own and as soon as possible!",
"Have mercy! I have a family, a daughter preparing to get married! At least give me some time!",
"For the last time, money for the barrel!",
"Fair enough, how many days do you need to get the money?",
"All right, all right. I'll tell Machado about your problems.",
"And how am I gonna get it? I told you, I'm on the verge of bankruptcy!",
"It's not my problem. Machado needs the money, and if I were you, I wouldn't push him.",
"All right, all right, here's your money.",
"Oh, you bastard! So you had the money all along!",
"I told you it was for my daughter's marriage! How am I going to marry her off now?",
"Stop whining. I hope never see you again. Good-bye.",
"Oh, not much! Just a couple of days, no more! I'll arrange a room in the tavern for you, and I'll meet you there as soon as I get the money together.",
"Sounds good.",
"Thank you, you are so kind to me, monsieur.",
"Keep your gratitude to yourself.",
"What do you mean?!... If it's about the money, I... I haven't collected it yet, eh... you need to wait a little longer.",
"You haven't the money yet, you say?! And with what you pay the murderers, then?!",
"What are you talking about?! I wouldn't dare, I wouldn't dare... I swear!",
"I would believe you if you weren't shaking and sweating from fear...",
"Is just... yes, that's it! I've got malaria! That's why I'm shaking, I'm sick, monsieur, that's the cause!",
"Stop explaining! I need the money, NOW!",
"But I already told you...",
"Shut up! Either you give me the money or I put a bullet in your head.",
"For God's sake, don't kill me!!... Ahem... Okay. Here's the money, the full amount.",
"Great. And consider yourself lucky, merchant.",
"Wh-what are you implying?!",
"That Machado doesn't like that you're shuffling his cards, haggler. He REALLY doesn't like it...",
"What?! You dare threaten me, little dog?!",
"Me? No, it's not me that's threatening you, it's Machado, and I just work for him.",
"Little dog?! Did you think that before you said it?! I'm going to ram it back down your throat!",
"What does that bloodsucker want with me?!",
"To buy your store.",
"What?! What's the matter with you? Are you out of your mind?! Tell Machado that it's not for sale!",
"Then I'll have to kill you.",
"Alright, I'll leave... but Machado will probably send in my place someone less patient than me.",
"You won't intimidate me. I'll keep my store!",
"Time will tell. (Try to slip your ring into his pocket discreetly).",
"Time will tell. (Walk away).",
"Yes, yes, of course!",
"But ",
"(you managed to distract Arnaud and discreetly plant him a ring, as well as a bag of money with your initials embroidered on it).",
"...",
"Hey! Get your hands out of my pocket, you scoundrel!",
"All right, all right, I'm leaving now.",
"That was the last straw! Who are you calling a scoundrel? I'll send you to hell!",
"You're bluffing! This town is full of soldiers, and if you lay a finger on me, you'll be hanged",
"You check it out! Argh!",
"You're right, to risk your neck for the pleasure of seeing your corpse...",
"Aha! I knew it! You don't have the guts!",
"That's it! You're pissing me off!",
"Scream or not, spreading your drool won't help the cause. Like I said, I'm here on Machado's orders.",
"You English dog! I'm not afraid of you! En garde!",
"Send regards to the devil, when you see him!",
"Get lost! I don't want anything to do with you!",
"Your wish are orders to me... But, I can only imagine how sad Sabina will feel about it...",
"Sa-Sabine?! What have you done to her?!",
"Nothing yet, but I have some plans... Unless you want to negotiate.",
"Anything! Just let her go!",
"Now we're talking! Sell your shop.",
"I don't get it...",
"Machado wants you to sell your shop. Otherwise give it to us, and he'll manage it.",
"Are you crazy?!",
"Well, since we haven't agreed, I'll let my men have some fun with your daughter...",
"Wait! All right! I'll pack my belongings and leave tonight. Just release my daughter, PLEASE!",
"Fine! Meet me at the tavern in three hours. I'll arrange a room there. When you hand me the keys, I'll give you your Sabina.",
"Good-bye, I'm going to Europe.",
"Good riddance.",
"You'll rot in hell!",
"Get lost!",
"Damn you! Here... wait a minute... Here are your papers. you are now the owner of the store. Now leave me alone, I must pack my things!",
"Pleasure doing business with you.",
"I've done what you asked. Here are the keys to the store and the necessary papers.",
"Great. I'll keep my word too - go to the port, you'll see your daughter there.",
"Now get lost, I'll keep your daughter, ha-ha-ha!",

};