string DLG_TEXT[66] = {
"Hello. I am ",
" an officer of His Majesty the King of France.",
"My name is ",
".",
"Have you come to see me just to talk, or do you have some business to discuss with me? ",
"Oh, actually, is just to talk...",
"I'm here on business, officer, rather important business.",
"I want to report a theft, Officer.",
"You are suspected of smuggling, and the theft of personal property from this man.",
"(Arnaud): What? This is absurd! I'm completely innocent!",
"(To Arnaud Matton): You are suspected of stealing personal property from this man.",
"(Arnaud): What? That's absurd! I'm completely innocent!",
"Then I must disappoint you, ",
". I have no time for idle talk.",
"Excuse me.",
"And what business is that?",
"It concerns a merchant named",
"Patric Cardone",
"Patric Cardone",
".",
"The man whose Indian relics were stolen.",
"That's right.",
"And what exactly do you want to tell me about this case?",
"Do you know where ",
"Lucien Bescanceny",
"Lucien Bescanceny",
" lives?",
"Of course I do. He's a very dangerous man, involved in all sorts of illegal activities.",
"Indeed. And if you pay him a visit, you'll find he has a lot of interesting information to share about the missing statuettes.",
"What makes you think he would want to talk with me?",
"Maybe he won't. But if he refuses, then search his room. You'll find the statuettes there.",
"What makes you so sure about that?",
"I've already been to his place and he confessed everything to me.",
"All right, I'll go and talk to him. But if this is some sort of scam...",
"It's no scam, officer, you'll see. Goodbye.",
"Bah! What an impertinence! You've been declared a criminal, there's a bounty on your head, and you want to tell me about a theft?!",
"The devil... I didn't think...",
"And what any of this have to do with me? Go to a civil court.",
"Me, a Captain, go to a civil judge? What kind of mess you've going on in here!",
"Oh... I'm sorry, I didn't know. That fact changes the matter and I'm listening to you carefully now, Captain.",
"From time to time I do business with Arnaud Matton, the shopkeeper\nDon't get me wrong, nothing illegal.",
"Please continue.",
"So this time I went to his shop and ask him if he had some business. He offered to buy me my cargo of sandal!",
"But the thing is, we don't get along very well, and he's always trying to scam me.",
"Are you sure about this?!",
"More than sure, officer! And when I pointed out to him that it was against the law, he got really mad. We argued, and when I came out of the shop I found my ring and wallet missing.",
"Let's walk to the shop to deal with this situation on the spot.",
"I'm following you, officer.",
"Go on...",
"Anyway, we had a big fight, and when I came out I found some personal items missing.",
"Let's go to the shop to deal with this situation on the spot.",
"I'm following you, officer.",
"(turning to Arnaud Matton): And that's what we're going to inspect. Do you mind if I conduct a search of your belongings and the shop premises?",
"(Arnaud Matton): I protest! Why should I be subjected to such humiliation?",
"(To Arnaud Matton): Your uncooperative attitude doesn't help you much, monsieur. Like it or not, I will search this shop and yourself!",
"(Arnaud Matton): Ah, well...If that is your will, conduct the inspection then.",
"(After a while, turning to Matton): So... Here are the items belonging to the monsieur who came with me... and there's also contraband in your basement\nI'm sorry to disappoint you, but until the official investigation is completed, I'm closing up your shop and ask you to come with me.",
"(Arnaud Matton): I'm innocent! I've been framed!",
"The court will decide that. Now, Arnaud Matton, you will come with me. And you, monsieur, I'll ask you to leave the premises.",
"All right...",
"(To Arnaud Matton): We'll inspect this now... So... what's this? Is this yours?",
"(Arnaud Matton): N-no...I don't know how it got there...",
"(Turning to Arno): Well...it appears to be theft...and that's at least confiscation of property and hard labour...",
"Hard labour? Send him to a quarry maybe is too much, officer. Perhaps we could make an agreement with monsieur Matton.",
"Well...I don't see why I should object to that.",
"Thank you, officer.",

};