string DLG_TEXT[98] = {
"I don't know who you are, but if you leave right now, I won't have to feed you to the sharks!",
"...",
"Why are you looking for ",
"Raoul Rheims",
"?",
"That's none of your business.",
"Silehard told me you'd be coming. He asked me to send him your head.",
"Well, here it is, right on top of my shoulders. You're welcome to try and take it!",
"Ah! It's the brave ",
", friend and hero to the downtrodden masses! What brings a noble man like you to seek out a villainous pirate such as myself?",
"Ah! It's you, ",
", whose ruthless and bloodthirsty reputation threatens to surpass even my own! What brings you to me?",
"I've come to give you this letter.",
"You're more of a clown than I would've expected. Just take this letter I've brought for you, so I can be on my way.",
"I think I've heard something about you, lad, but I can't quite remember. Who are you?",
"My name is ",
", and I'm here on business. I brought you a letter.",
"A letter, you say? And from whom, I'd like to know.",
"Open it and read it, then, or do I have to give you the sender's name?",
"Yes, damn it! And make it quick before I rip your head off!\nAnd also change your tone, rookie, remember who you're talking to.",
"Well, that answers my question. The sender is the English Governor, ",
"Robert Christopher Silehard",
".",
"Robert Christopher Silehard",
"? Ha! The old rascal wants my help again, how interesting. What are you standing there for? You delivered the letter, so get lost!",
"...",
"Wrong. Let me explain, girl. This is my town, this is my island. And everything that happens here, happens with my knowledge and consent.",
"So you're what, then -- a pirate chieftain?",
"I prefer to think of myself as governor of an independent colony. But I'm still waiting for your answer.",
"What kind of town is this? Whenever an unhappy girl goes in search of her lover, there's a big fuss about it!",
"Lover? Haha, you don't say so! Miracles still take place in this world! Why did he leave you?",
"Tell me, was he here? When? Where did he go?",
"He was here...making repairs after a storm. But I don't know where he sailed. He didn't tell. All right, take your leave now.",
"...",
"Who do I see! The mate who let my ship go down!",
"What do you mean?",
"The Black Pearl'. Barbossa mutinied along with my men, took her and stranded me on a deserted island.",
"I see you managed to escape...",
"Yes, I've got a few tricks on my sleeve, mate. By the way, you can be glad - Barbossa and his crew are... immortal. And they will bring back the Pearl in no time at all.",
"Maybe, but...",
"No buts, lad, that's the way it's going to be, you can believe me. The curse that hangs over these folk won't be lifted just like that.",
"We'll see.",
"What brings you to me?",
"Nothing, really.",
"Ha! Already afraid to show up alone that you need to bring some lad with you?",
"Calm down, let's talk about the matter.",
"I don't know who you are, but if you leave right now, I won't have to feed you to the sharks!",
"...",
"(Turning to you): Bah, you're the mate who sunk the 'Pearl'!",
"So what of it?",
"About the matter... what does this have anything to do with me?",
"What do you mean?! It's your people who are taking me out of business!",
"Since our problem has been ...resolved, we can continue with the business proposal. Basically, lad, 'service' is an overstatement. All I need from you to do, is return the 'Black Pearl' to me.",
"She sank! I sent her to the bottom of the sea myself.",
"I'm disappointed! You failed my mission!",
"I'm sorry...",
"You sunk her. And now I'm going to send you to the other side as well, Argh!",
"The 'Pearl' is moored in my port! I can't believe it!",
"You better believe it. And now give me my reward.",
"Well earn it... only I changed my mind about giving it to you.",
"I could use a lad like you. I'll double what Machado pays you, what do you say, mate?",
"Ha! That's the best offer I ever had! Sure, I'll take it!",
"I'm not for sale, keep that in mind!",
"Loyalty is a good trait, but come on mate, it's my business to offer, and your business to refuse. Nothing personal, they say, he-he.",
"Stop luring people away from me! And let's get back to matters! Why on earth would your people get in the way of my business?",
"smuggler_line_3",
"My people getting in your way? Are you crazy? I use your 'excellent' services from time to time, and you accept our goods without unnecessary questions. I am the one who has more to lose from this all matter.",
"Hmm... Then who is sinking my ships? I know from a good source that it's the Brotherhood's fault.",
"Did it ever occur to you that it might have been the men from Douwesen?",
"I've already spoken to them, they also deny it.",
"Then I don't know, but my men certainly have nothing to do with it, so look for your 'pirates' elsewhere.",
"Alright... I apologize for this interruption then.",
"Fine mate, goodbye.",
"Goodbye.",
"That's great!",
"You bet! I've always wanted to be a pirate!",
"(Machado to both): No! This is not the way to do it!",
"Calm down, mate, go back to your place and live in peace.",
"(Machado to both): Argh! I'll go back, but you're not!",
"It's a pity, but I'll have to kill you.",
"Did it ever occur to you, mate, that the curse that hangs over Barbossa's men, allowed them to bring back the 'Pearl'?",
"To be honest, no...",
"So that's what happened. Surely, you've heard that the 'Pearl' used to belong to me, and I'd like it back.",
"You want me to fight the cursed again?!",
"Fear not! First, you must have weakened them greatly by using that ancient artifact...",
"And secondly?",
"Secondly, I'll give you one lad to back you up.",
"You got it, damn it.",
"That's great! Once you've got the 'Pearl', come back to me.",
"Alright.",
"I'm very sorry! Now leave me alone.",
"Goodbye.",
"We'll see about that. Defend yourselves!",
"You're one to talk!",
"Here's your reward, and let me offer you my own ship as a substitute.",
"I wouldn't think of refusing the offer!",
"I shall take it by force then!",
"Defend yourself!",

};