string DLG_TEXT[40] = {       
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"To discuss some business with you.",
"I'm sorry to take your time. Good bye.",
"So, what is the reason to distract me from important matters of state?",
"I'd like to know if you need my services.",
"This is merely a courtesy visit and nothing more.",
"In that case, I will ask you to leave my office and not to interfere with my work.",
"Yes, of course. Sorry I disturbed you.",
"I'm listening, ",
".",
"I'm here to collect the bounty on Mean Harry's head.",
"Yes, I've got a job for you, Captain.",
"And what's that?",
"You have completed my assignment, congratulations! Here is your reward.", 
"Thank you. It's been a pleasure serving you.", 
"I'm sorry, but I have nothing to talk to you about right now.",
"I need you to sink the ship '",
"quest pirate",
"', presumed to be in the waters of the colony ",
". If you complete this mission, I will pay you ",
" gold pieces.",
"I'll take the assignment.",
"Thank you, but I'm not interested.",
"Oh! Yes, I've already heard rumors of your deed. On behalf of the whole colony, I appreciate what you have done.",
"Appreciation is good, but a reward is better.",
"And you're a joker too, ha-ha. But don't make that face, I beg you. Here's your money.",
"Thank you, I am your faithful servant.",
"Of course, but as far as I know you've made a bet... Well, and all such bets go through our treasury office\nAfter deducting all sorts of taxes and such trifles, I'm prepared to pay you six thousand piastres.",
"What the hell! The reward was ten thousand!",
"I'm afraid I can't help you. Here's your money, and from now on... try to calm down when the men in power speak.",
"As you wish... (pompous parrot).",
", you're accused of murdering a man. You were found right next to his body. What do you have to say in your defence?",
"I had nothing to do with his murder. I was told that he could give me some important information. When I entered the room, he was mortally already wounded.",
", I was informed that a man had been seized on the way out of town. A bloody knife was found on him. He confessed having committed the murder at the inn. You may be free to go.",
"Thank you. I knew that justice always prevails in Conceicao, so I am not the least bit surprised at the favourable outcome of my case.",

};