string DLG_TEXT[101] = {
"Who are you, ",
"?",
"I'm ",
", captain of the '",
"'.",
"My name is ",
", and I am, of course, the governor of this colony, as you may have guessed.",
"Happy to make your acquaintance, monsieur.",
"Oh, I've heard a lot about you, ",
". It is said that you are a fortunate captain, and have accomplished many glorious deeds.",
"I'm glad you've heard of me, monsieur.",
"So, what can I do for you, ",
"?",
"I am a free captain. Do you require my services?",
"I'm afraid I have to refuse the assignment you gave me, monsieur, a pirate ship is beyond me.",
"I've just came to talk.",
"Talk? What do you take me for, ",
"? I'm an officer of the state. I don't have time for a talk!",
"Sorry, monsieur, I was just leaving.",
"There's a war going on with England, and I don't see how you can help me or my country, ",
".",
"That's too bad, monsieur.",
"Yes, I think I can find you an assignment.",
"Very well! What will it be?",
"I've already been informed of your victory over the pirates. Congratulations, ",
", it was a splendid victory!",
"A pleasure to serve you and France, monsieur.",
"Yes, I have an assignment for you, Captain.",
"And what is that?",
"I've already been informed hat you have completed my mission. Congratulations, here's your reward.",
"Thank you, monsieur. It's been a pleasure serving you.",
"I can't say I'm happy to see you, but I don't have any choice - you've very influential friends.",
"We try, monsieur.",
"So, one of the most wanted men in the archipelago appears right in front of me? Guards!!!",
"If you do not call off your men at once, I will order the death of a certain lady by the name of ",
"Virginie d'Espivant",
". I don't believe her father will be happy to learn that you could have prevented that.",
"I'm listening carefully. What do you want?",
"On my ship I have a lady named ",
"Virginie d'Espivant",
"...",
"I need you to sink a ship, '",
"quest pirate,",
"', presumed to be sailing around the colony ",
"\nIf you complete this mission, I will pay you ",
" gold pieces.",
"I'll take the assignment.",
"Sorry, but I'm not interested.",
"You've found her?! Thank God! But, dare I ask, is she staying on your ship as a prisoner?",
"Exactly, monsieur. Although she came to me quite by accident.",
"Of course not! On the contrary, she's my guest of honour.",
"I'm pleased to hear it. How did you find her?",
"Oh, it's a long story, monsieur. I believe ",
"Virginie d'Espivant",
" will tell you herself, if she deems it necessary.",
"Yes, of course. I dare not delay you any longer\nPlease accept this sum as my gratitude, and I'll arrange for the girl to be escorted from the port when you bring her ashore.",
"Consider it done, monsieur.",
"Devil! So you have it in your hands?!",
"Yes. And, I beg to differ, she got there by quite an accident.",
"Anyway, back to business. What do you want for the girl's release?",
"Unobstructed passage to my ship and money, of course.",
"And how much do you expect to get?",
" I think 7000 gold will be enough.",
"What? Are you out of your mind?!",
"I don't think there should be bargain involved.",
"All right. Here's your money. And I guarantee safe passage to your ship, you have my word. Let the girl go.",
"Your guarantee? I'm told you're a man of your word, but I'm not taking any chances. You'll have the prisoner as soon as I'm out to sea.",
"Very well. But be warned: cross me, and I'll order every available ship at my disposal to bring me your head!",
"Agreed.",
"I see. Well, I am forced to say this - I have to pardon all of your transgressions against my country.",
"What an honor, monsieur!",
"Mind your sarcasm! If this were up to me, you'd be hanging in the square by now! You should thank the young lady you saved for my mercy.",
"My gratitude knows no bounds, monsieur!",
"Yes, I can see that. What's more, I must pay you a reward\nHere it is. Now do me a favor, and leave!",
"With pleasure, monsieur.",
"There is a pirate ship in our waters blocking trade routes, and our fleet is engaged in a military operation.",
"You want me to sink that ship, monsieur?",
"I think I know what you're going to ask of me, but I must refuse.",
"That's right, ",
". I'll pay you 5000 gold to sink the warship.",
"Agreed. I'll take the assignment.",
"Military action for that amount is too little for me, monsieur. I shall be forced to decline unless you increase the reward.",
"I'm glad your heart is full of courage. May fortune be with you, ",
".",
"Have no doubt, monsieur. I'll handle this assignment.",
"Do I look like a merchant?! Don't bargain with me! Either you take this job or you can go to hell!",
"All right. I'll sink the warship, monsieur.",
"With such a reward, find yourself another Captain!",
"Take your reward, and don't go too far. I may have more assignments for you later.",
"Certainly, monsieur. I dare not disturb you any further.",
"It's a pity to find out that you're such a coward.",
"Life is more precious than gold, monsieur.",
"Monsieur! I will complete this task only to have you take that back!",
"You disgust me. Leave my office at once!",
"As you wish, monsieur.",
"Well, well, well. Thief... I'd even say petty thief, and a captain too. Shame on you, monsieur!",
"Allow me to explain! This is not my fault!",
"And you insist? Your guilt is proven! There is no single doubt that you stole Arnaud Matton's family ring!",
"But I didn't steal it! I demand an investigation! I'm a Captain! Isn't my word worth anything?",
"You're boring me. Guards! Take him away!",
"Blasted hell! Allow me to explain!...",

};