string DLG_TEXT[66] = {
"What do you want?! Can't you see I'm busy? I'm going to kill that bastard, then we can talk!",
"Hey, I won't let you kill a man in my sight, who, by the way, is much worse with a sword than you are!",
"I think you can sort this out without my help, goodbye.",
"Did you see how I did it? With one cut...",
"Yeah, great",
"That Voysey bastard told me he was a great navigator\nBut that didn't stop him from sending my boat to the bottom. He fed all my cargo to the fishes. Now he won't be bragging about it anymore\nI was a good captain. By the way, do you have room for me on your ship?\nTrust me, you won't regret it. Ask anyone and they'll tell you that Nigel Blythe is the best pirate in these waters.",
"No, I'll do without you.",
"You certainly know how to boast, but we still need to know how you really are. If you're half as tough as you talk, we'll get along fine.",
"You won't regret it! I just need to know how much you're willing to pay me. I'm not going to work for free, you know.",
"How much are you asking?",
"3,000 gold, and my soul is yours.",
"It's a deal. Welcome to the crew.",
"You think highly of yourself. I'll consider your offer...Later.",
"Will you take me on your ship? I'm only asking for 300 gold.",
"No, I'm sorry, I don't have room.",
"All right, it's a deal. I'll give you 300 gold.",
"What are your orders, Captain?",
"I'm listening.",
"Just taking a walk.",
"None. At ease.",
"Let's talk about our tactics during the boarding.",
"Cap, is that you?! How fortunate you came up! I just made a very good deal",
"What deal?",
"Good day, captain.",
"Why the hell did you leave the ship?!",
"I just made a 10,000 gold bet with the locals that we could sink Mean Harry.",
"What are you talking about? You're at it again?!",
"What do you mean, Cap? I agree the chocolate deal wasn't very good, but there's a whole ten grand at stake here!",
"That's it, I'm sick of your antics! You're fired!",
"Give up that stupid bet. Right now. And I've had quite enough of your 'initiative' already!",
"Tell me more about this Harry.",
"It's all pretty easy, Cap. We've got a month to sink that bastard hanging around.",
"I said - tell me ABOUT HARRY!!",
"Oh, come on, Cap, don't make such a fuss. So, this Harry hasn't got any more than a piddling little ship, maybe a corvette or a frigate, I don't know for sure.\nAnd the local governor has offered 3000 gold for his head. We'll get another 10000 if we sink him within a month.",
"A frigate or a corvette?! Nigel, are completely out of your mind?! To hell with this bet!",
"It's worth the trouble. We could try and take on that Harry.",
"I knew you'd fall for that, Cap! You'll see! You and I are going to do great things!",
"Yeah. That last part of your statement doesn't inspire me much.",
"Oh, all we have to do is deliver a load of chocolate to Isla Muelle. Can you believe they're paying us 2,000 piastres for it?",
"Are you crazy?! Who let you make deals in my name?!",
"Come on, it's a bargain. I was a captain myself, and I have a sense for this sort of thing.",
"Just like that, huh? You're fired!",
"All right, you've got half an hour to break that deal, and then get back to the ship. Is that CLEAR?!",
"You're lucky that I don't want to risk my reputation by canceling that deal. But if you pull anything like that again, you're on your own.",
"Take it easy, Cap. And don't give me that look, I can explain everything.",
"Yeah, try harder.",
"Thing is, that dirty pig whose ship I sank? He seriously screwed me over a few months ago.\nI couldn't just let him go after that, could I? I mean, that rat sold me spoiled goods!",
"Oh, God, Nigel, how many more disasters will you bring me?! That's it, you're fired!",
"Well, I think you've done the right thing.",
"Nice job on them, Cap! That'll show em...",
"Shut up, Nigel. You're fired!",
"YYeah, yeah, but remember! Make sure this is your last stunt, or I swear I'll skin you alive!",
"Whatever you say, Cap.",
"All right, get back to the ship.",
"I got nothing to talk to you about.",
"...",
"You shouldn't do that, Cap. I'm only looking out for our best interests.",
"Shut up! How many tons of this chocolate of yours do we have to haul?",
"Only 200 tons, Cap.",
"Hmm. All right, we've got space for that. Now get back to the ship!",
"You're crazy? And where do you expect me to put it? In my cabin? You've got half an hour to call this deal off!",
"Yes, I'm listening.",
"I don't want you to come aboard with me.",
"I want you to come aboard with me.",
"Alright, Captain.",
"...",

};