string DLG_TEXT[25] = {       
"...",
"...",
"Who are you?!",
"I... well... it's...",
"Hold on a minute, monsieur, we have a few questions for you.",
"Yes?",
"Are you ",
"That's me, what would be the problem, exactly?",
"You're suspected of theft, sir, we'd like to search you.",
"Really? that's ridiculous! But since you're asking, go ahead.",
"For some soldiers to go through my pockets?! Are you out of your mind?!",
"Thank you for your cooperation. So... this one belongs to you too, monsieur?!",
"That ring? ... I have no idea how it ended up in my pocket!",
"Well, come with us, then.",
"What the?! All right, all right, don't grab your swords, I'll submit, because I'm innocent.",
"Oh, no! It's all rigged and I'm not going anywhere with you!",
"All right, now hand in your weapons, sir.",
"Here you have, I have nothing to fear.",
"My sword? Isn't that too much to ask?!",
"Thank you, now come along...",
"I'm following you.",
"In that case we'll have to detain you by force.",
"Ha! Try it!",
"Just someone who wants to see you dead. Send regards to the devil, scoundrel.",
"You devil!",

};