string DLG_TEXT[60] = {
"I heard that you want to see me. So, what business do you have for me?",
"I'd like offer my services.",
"You must be a captain. What's your name?",
"My name is ",
", captain of the '",
"'.",
"Good, I'll remember your name. Now, please, tell me what made you come to me.",
"I'd like to talk business with you.",
"Nothing. I'll take my leave, if you'll allow me.",
"You can leave. But don't disappear completely, it's possible I'll have plans for you.",
"As you say, mijnheer.",
"I'm listening, what brings you to me?",
"Business, mijnheer.",
"I was just leaving.",
"Then let's talk business.",
"I am here on behalf of those women standing by your entrance.",
"Your mission is a success. The missing children have been returned to their parents.",
"I need to speak to you about a man who is under your protection.",
"Your mission is accomplished, mijnheer.",
"Yes, I have a assignment for you, Captain.",
"Please tell me, what is it.",
"I know that you have completed my assignment. Congratulations, here's your reward.",
"Thank you. It has been a pleasure serving you.",
"I don't have anything to discuss with you at the moment, mijnheer.",
"I need you to sink the ship '",
"quest pirate",
"', presumed to be in the waters of ",
". If you complete this mission, I will pay you ",
" gold pieces.",
"I accept the assignment.",
"Sorry, but I'm not interested.",
"Yes, I already know that, here is your reward. I hope that in future I will be able to use your services.",
"Rest assured of that, mijnheer.",
"Well, well, and who do you have in mind?",
"A certain corsair by the name of ",
"Bernardo Gamboa",
", mijnheer.",
"Ah. That man?! And what do you want me to say? As far as I know, his reputation is stainless...",
"You would be wrong. From what I know, he kidnapped a girl from your town.",
"Ah, ah, ah. Are you sure about that? I don't want to insult him unjustly.",
"If you don't mind, I will investigate this privately. No one will know of your involvement. If he didn't kidnap this girl, your relationship with him will remain intact, if he did, then you would show to everybody how just and powerful you are.",
"Hmmm... That is not unreasonable. Indeed, I don't risk anything in this case. You may find out what's going on. If your mission ends successfully, I'll reward you. But, since this is your initiative, it will be a modest sum.",
"Thank you mijnheer.",
"Remind me, what were we discussing?",
"We were talking about a kidnapped girl.",
"Ah, yes, I recall. As I understand, she really was kidnapped.",
"Yes. The scoundrel didn't want to give the girl back and was slaughtered by his own men.",
"Well, no pirate - no problem. Here is your reward. You can leave my room now...",
"As you please.",
"Ah, that's what you wanted to discuss...",
"Honestly I don't understand why you turn a blind eye about it, isn't it your job to ensure the safety of the residents of the colony?",
"Captain... I'll forgive your criticism of me this once. Don't do it again if you don't want to lose my goodwill\nAs to those women...I see you're an smart man, so, I will tell you something.",
"I am all ears.",
"Two soldiers were found dead today. One of them had a piece of a red cloth in his hand\nA few hours earlier, a captain of a merchant ship entering port, saw a frigate sailing away from the island.",
"And how can that stop an official investigation?",
"Well... It's obvious that the kidnapped children were taken off the island. Under the circumstances, and expedition for search and rescue is unaffordable\nMoreover, finding them is unlikely, to say the least, you must realise that, they could be anywhere\nBut, if you're so concerned about the women's grief, I can suggest you to look for the children\nI promise that if the search is successful, I'll show you my gratitude.",
"All right, I agree, but first I'd like to know where I can find a witness who saw the frigate.",
"No, I don't want to spend my time on such nonsense.",
"You accept? Perfect! I presume you can find the witness in the tavern, the captain who sighted that ship.",
"Thank you, I take my leave now.",

};