string DLG_TEXT[306] = {
"Please, introduce yourself. I'm not accustomed to talk to strangers.",
"My name is ",
", and I'm captain of the ",
".",
"Captain ",
". Glad to see you in good health. What brings you to me?",
"Hello Captain ",
". Tell me what you've come for.",
"I'm listening to you, Captain ",
". What business do you have with me this time?",
"I have business to discuss, sir.",
"I'd like to know if you need the services of an able captain.",
"Just a courtesy visit. Goodbye.",
"Well, Captain ",
", I can see by your face that you're in a hurry to tell me something. What is it?",
"You may already know this, but the English settlement of Oxbay has been attacked.",
"Have you returned with the prisoner? Where is he? I want to see him.",
"I am sorry, sir, I haven't. The fact is that he escaped before I even arrived on Oxbay.",
"You have my full attention, captain.",
"However, let's discuss this later, sir.",
"I've just returned from Oxbay, sir.",
"I'm pleased to report that the mission is completed.",
"Alas, I have no need of your services at the moment, Captain. Although feel free to ask me later.",
"I have business to discuss, sir.",
"Alright then, sir. Goodbye.",
"Very well, Captain ",
", but from now on, think more wisely before you seek an audience with me. I'am a busy man.",
"Do you need my services, sir?",
"Just a courtesy visit. Goodbye.",
"Hahaha, don't be modest, captain. Maybe they started it first!",
"Well, as a matter of fact they did, sir.",
"Be as it may, I'm pleased to give your reward for defeating the pirates.",
"Thank you, sir. There is something I'like to discuss.",
"Thank you. Do you need my services, sir?",
"I appreciate that, sir ",
", but I must be going.Goodbye.",
"Unsettling news... Damn it, how can there be pirates in these waters?\nI was assured that the squadron under Captain Tomlison had captured all those scoundrels!",
"These were not pirates, sir. These were French ships and troops.",
"What?! By the devil! I saw this coming. His Majesty should have made a warning action a long time ago!\nTell me more. How did you escape? What kind of forces did the attackers have? Are you sure it was the ships of the French fleet?",
"Absolutely, sir. French banners were the first thing I noticed.",
"All the worse for us... There's hardly any gold in the colony's coffers, and I don't know how we will defend our homes\nI am afraid, ",
", this will affect you as well.",
"Me? In what way?",
"We were talking about the French squadron.",
"Hmm. I don't like the sound of that. I'd better go, sir.",
"The thing is, there are only two warships left at Captain Tomlison's disposal - the third was badly damaged during the campaign against the pirates\nThereby, I have no other choice but issue an order of dispose private vessels to be armed and commanded. I'm sorry, Captain, but this order will also affect your ship.",
"What? I'll not let you confiscate my ship!",
"Ah, yes...yes...So what kind of ships were used to lay siege to the fort? What kind of arms did they have? How many soldiers?",
"I counted five ships. Clearly I saw a 24-gun brig and a 20-gun schooner. The rest of the ships were obscured by the fog.",
"Dear ",
", to my regret, I can't let you go. I must commandeer your vessel and set it against these invaders.",
"Excuse me, sir, I didn't quite hear what you said...",
"If you resist, Captain, I will be forced to take your ship from you. Understand, I have no alternative in this situation.",
"Then let me offer you an alternative. My ship and I are at your service.",
"You're going to force me? Go ahead and try it!",
"Your information is not of great help, captain. That's unfortunate, because your situation is not enviable, ",
".",
"What do you mean, sir?",
"An excellent decision, Captain ",
". I am glad we have found an solution that suits us both. Now, to your task\nI think it would be best that, instead of replenishing Captain Tomlinson's forces, you act on your own.",
"What do you mean, sir?",
"I'll ignore your insolence for now, captain. But keep in mind, there is a loaded gun in my desk, and there are guards outside the door. Now let me continue...",
" Then I want to command my own ship! I am hired for your service, sir!",
"My hope is that you may be the key to obtain more information about the French forces\nWith your skills, you could infiltrate the occupated colony of Oxbay, and gather information from the local citizens\nPerhaps you might even be able to listen to the conversations of the French themselves.",
"Are you suggesting that I sneak into the captured city and gather information about the French plans?",
"And what about the payment, sir?",
"Exactly! Then we'll know what to expect, and more importantly, how can we liberate our colony.",
"Indeed...",
"By the way, sir, how about a portion of the payment in advance?",
"If you need the money that badly, Captain, then take this 1,000 gold and spend it preparing the ship for sailing. But bear in mind that I will deduct it from your salary at a later date.",
"Thank you, sir.",
"Unfortunately, Captain ",
", I have no means of giving you an advance at the moment. All funds will be spent in preparing the squadron and the fort for warfare.",
"How inspiring.",
"A word of advice, Captain. Don't try to deceive me. If you slip away, instead of doing your duty\nI'll declare you a pirate and order Captain Tomlinson's entire squadron to pursue and capture you.",
"If there is anything left of it after the battle with the French!",
"Well... it seems we've strayed from the matter. Captain, your mission is to gather as much information as you can about the French forces\nTalk with the local townsfolk, go to the tavern - I trust the enemy will be looking for ways to relax after the battle.",
"Indeed...",
"Listen, ",
", treat it as a necessary evil. After all, you should feel fortunate. You've been accepted in the service of the Crown, a position many aspire to hold\nBesides, I assure you that you will receive a generous compensation. Good luck!",
"I hope to see that generosity soon. Goodbye!",
"Congratulations on your return, captain. Report your findings.",
"The local population treats the invaders with resentment.",
"Rightfully so. What have you learned of the French future plans?",
"They're waiting for a ship carrying ammunition, which is now at the harbour of Falaise de Fleur. After that, they'll intend to attack Redmond.",
"The situation is quite clear. Thank you for your service, ",
". Here is 3000 gold as payment.",
"Thank you, sir.",
"Your new assignment is to make sure the ammunition ship doesn't reach Oxbay. When we finally face the French in battle, the less powder they have, the better.",
"You want me to sink the barque?",
"I don't care what becomes of it. You can seize it. The main thing is that the French don't get that ammunition.",
"But the ship is guaranteed to be escorted by a convoy.",
"I see. See you later, sir ",
".",
"Most likely, but, ",
", perhaps the best results can be achieved not by directly attacking the convoy, but indirectly\nAfter all, you are free to visit Falaise de Fleur in the meantime, and find out how things are going there. Maybe you can do with words and money what would be difficult to do with guns.",
"Sounds vague, but I'll give it a try. All the best.",
"Glad to hear it, ",
". But still, don't forget the chain of command.",
"We freebooters aren't used to such formalities...",
"Then remember that as long as you serve me, you serve the Crown. Be mindful of this, captain.",
"Yes, sir.",
"I understand you managed to squeeze the life out of the French squadron?",
"Absolutely, sir.",
"After you set sail, I sent another captain to Oxbay. She managed to discover a large cave on the island near a secluded beach\nI plan to hide a garrison of soldiers in this cave. Once they're in place, We'll make a coordinated attack, both from sea and land, to liberate the city.",
"A reasonable plan, but I doubt that there is enough room on my ship for an entire detachment.",
"No need, captain. I've already seen the transport. Your task will be to escort the transport ship along its route\nThe sloop 'Albion' commanded by Captain ",
"Ewan Glover",
"Ewan Glover",
", is anchored in port. ",
"Ewan Glover",
" will wait for you at the town gates.",
"I see. Then, I suppose I shall take your leave...",
"Wait, I'm not finished. You have to escort the 'Albion' sloop to the port of Greenford on Oxbay\nThere, a local man, loyal to the Crown, will show you the way to the cave\nAfter that, once again you'll infiltrate Oxbay, and seek out one of our agents concealed in the town.",
"That's a lot to remember. So what am I to do when I reach the agent?",
"He has some very important information. That's why you must do your best to make sure he survives to convey that information to us.",
"And the agent's name?",
"Counterspy",
" it's his name\nHe has made contacts with the local citizens. If you can't find him straight away, ask around. But do so discreetly.",
"Alright. Now, when may I expect payment for my last mission?",
"Don't worry, ",
", here is your gold.",
"Nice to hear that, sir.",
"Now you can go, captain. I'm looking forward to your next report.",
"Goodbye, sir.",
"Well, Captain ",
"..., I had thought better of you. But what's done is done. At least part of the task is completed.",
"But...",
"Congratulations, captain. Honestly, I can't tell you what a relief it has been since I took you into my service.",
"Thank you, sir.",
"I am not interested in your explanations, captain. I heard your report from ",
"Counterspy",
" and he explained what happened. I am just disappointed that because of your failure, there will be more blood lost in this war.",
"I am sorry, ",
", I did my best.",
"... Well. These things do happen. After all, thanks to you, we've had the opportunity to rebuild our squadron.",
"So what's is my next task?",
"You're going to participate in the assault of Oxbay as part of our squadron. It goes without saying you need to prepare. \nI hope this will be enough for you. And, I have deducted a portion of your payment due to the loss of the 'Albion'.",
"When are we going to set sail?",
"Soon. For now, do whatever you need to in the city, and when the time comes, you'll be notified. And get some rest and relax. Every captain should have a hearty evening in the tavern after a sail.",
"Far from it, but in your words there is a kernel of truth.",
"That's not important. My messenger will find you. Good luck, captain.",
"Farewell.",
"counterspy",
" has just informed me of your exploits. And ",
"Ewan Glover",
"Ewan Glover",
" seemed quite satisfied with your cruising together.",
"Hmm.... I can't think of any exploits.",
"Ha. You're too modest. Well, here is your reward. I suggest you make your vessel seaworthy. You'll have to set sail again very soon.",
"And what kind of mission will it be this time?",
"The siege of Oxbay. You'll join our squadron which is going to free the island.",
"And when will the squadron set sail?",
"Soon. For now, do whatever you need to in the city, and when the time comes, you'll be notified. And get some rest and relax, every captain should have a hearty evening in the tavern after a sail. I'll send a messenger for you there.",
"All right. I'll take my leave now.",
"Ah?! What?! What are you doing here?! ",
"? ",
"Danielle",
"?!!",
"Sorry for interrupting your slumber, dear governor, but we have questions that need answers.",
"What do you mean? Leave now, and I shall consider sparing your life!",
"I think you misunderstand your position, governor ",
". You no longer give the orders. And if you so much as think without asking, then ",
"Danielle",
", you may find yourself compelled to exercise your elegant fencing techniques.",
"All right, all right, please! Don't be so unruly. Of course I'll answer all your questions... Just sheath your sword, ",
"Danielle",
", please contain him! His look makes me nervous.",
"Be quiet and listen. We know all about your dealings with treasure, and you have much to answer for.",
"Please, you devils, don't hurt me!",
"A flattering assessment, but for now, you should tell us what you know about the idol that opens the doorway to the palace.",
"I'll not tell you scoundrels anything! Guards!",
"Oh no! ",
"Danielle",
"! Let's head for our ships!",
"Escaped?! How could it be?",
"They didn't explain. Only that the search for the escapee is still ongoing.",
"Damn! This situation is getting out of hand!",
"Excuse me, sir, but I have good news for you.",
"Then say it right away, ",
", what are you waiting for?",
"I found a lead to the captain who betrayed England and your trust.",
"Raoul Rheims",
"? It's true. It's not the worst news for today.",
"I am ready to get him now, if it pleases you, sir.",
"Of course, fair winds to you, ",
". And captain...this time you need to bring him back. And keep in mind that until he gets here, he shouldn't speak to anybody, even you. Is that clear?",
"Yes, sir. I'll do everything as you say.",
"! You've been away for such a long time, I've begun to worry about you!",
"I am all right, and I've completed your task.",
"To be honest, I am surprised, I didn't expect positive results from this expedition. So, you managed to get the whole collection for me, did you?",
"Yes sir, except one idol. It was bought by some stranger.",
"One idol? Let's have a look at what's missing.",
"Here, see for yourself, sir.",
"It's true, one idol is missing, what a pity.",
"Do you want me to find this one, too, sir?",
"No, don't worry about it, ",
". Though I appreciate that you are ready to help, I'll send someone else after the idol. Instead, I have another task for you\nOh, yes, I almost forgot. Here is the payment promised to you.",
"Thank you, sir, and I'm curious to know what mission you have for me.",
"Yes, well.... Several minutes before your arrival, ",
", I was informed that a pirate was captured in Greenford. This particular pirate has always managed to slip from my grasp many times and has annoyed me greatly. I want you to bring this pirate to me.",
"Sounds simple enough, sir. Can I go?",
"Just a moment, ",
". I appreciate your enthusiasm, but that's not all.",
"Sorry, sir.",
"On your arrival to Greenford, talk to the prison commandant,  ",
"Greenford Prison Commendant",
"Greenford Prison Commendant",
". Show him this letter, and he will release the prisoner into your custody\nWhen you return, you'll receive 5000 gold.",
"Understood, sir.",
"I hope your return means that you have completed my task and have delivered the letter to it's recipient.",
"Yes, sir. But it was a challenge, the manners of pirates leave much to be desired. Rest assured, he's got the letter.",
"Well done. I hope the next task will also be as skillfully handled, ",
".",
"And what might that job be?",
"Hold on, no need to rush, ",
". First, let me give you your reward.",
"Thank you, sir. It's a pleasure to work with you.",
"And your flattery is always appreciated, ",
". Now, let's get down to business.",
"I'm all ears, sir.",
"Your next endeavor, ",
", is something of a personal matter for me. In my position it can be a bit unethical to use the Imperial forces for one's own business. So I'm especially keen to use you.",
"I am intrigued, sir. As long as you don't want me to take on the French fleet alone.",
"You have a sense of humor about you, ",
", but let's not get distracted from the main subject.",
"I am sorry, sir.",
"A ship was captured by pirates several days ago, '",
"pirate captain 06",
"', headed for Europe from New Light. As it was passing by our colony, pirates struck\nBesides the usual trade goods, there were several golden idols on board. These are rare Incan treasures that I have ordered for my collection\nI managed discover the pirate lord that ordered the capture. His name is ",
"Alistair Garcilaso",
"Alistair Garcilaso",
". They say he and his gang of butchers and thieves are hiding in the Douwesen jungle, but I don't know where exactly\nI need you, ",
", to find them and bring my collection back somehow. I realize that this is not the easiest task, and that's why I'll give you 10000 now, and an equal amount if the mission is completed successfully\nAs I mentioned, I'm loathe to use army personnel for personal matters. And, the mere thought of landing troops on Douwesen...well, we'd risk a conflict with the Dutch\nYou're my only hope.",
"Finding men who don't wish to be found is hardly an easy task, but I think I serve you well, and this is a generous sum, indeed.",
"Well, if you accomplish this, it's well worth it, ",
". So, without further to add, here is your payment. Good luck to you.",
"I'll return as soon as I can, sir.",
"You've returned, ",
", but where is ",
"Raoul Rheims",
"? I don't see him with you.",
"I have failed, sir. I lost the trail of him in the smuggler's den.",
"You disappoint me, ",
", such a simple mission, and you couldn't complete it? I had a higher opinion of you.",
"Sir, I apologise, but I almost got killed in the smugglers' den. Nonetheless, I managed to find out that ",
"Raoul Rheims",
" is now planning to go on an expedition to an unknown location.",
"Well, it's not my nature to chastise failure, especially when an earnest effort's been made. But I hope you'll not fail your next mission.",
"Thank you for trusting me, sir. I'll do my best to not let you down again.",
"You're welcome, ",
". By the way, here is the 5000 gold that I promised to give you, although it's not fully deserved.",
"Thank you, sir. Your generosity amazes me.",
"Enough of this, ",
". You needn't flatter me. Now. Let's talk business. I understand you've been to the pirate's nest\nSo, now that you know where to go, I need you to take this letter and deliver it to the pirate lord. He goes by the name of ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
". \nNow, before you become alarmed, I'm sure you're curious what possible communication I might have for this low devil. You may recall that ",
"Raoul Rheims",
" now knows too much for me to let him escape\nIf you aren't able to catch him, these pirates may. So when are you going to start on your journey?",
"My ship is ready to sail, sir.",
"Perfect. Then set sail immediately. After you've done your duty, return to me for the reward. Is everything clear, ",
"?",
"Yes, sir, I will set sail immediately.",
"Good, no one can disturb us.",
"Go ahead, sir.",
"First, I'd like share joyful news - Oxbay is free\nYou helped us greatly in our quest for victory. Thank you.",
"You're welcome. And perhaps you have something for me next?",
"Of course. I want you to bring me the person who betrayed us and put our colony in such peril! His name is ",
"Raoul Rheims",
"Raoul Rheims",
".",
"If I may ask, what did he do?",
"Inquisitive! I like that. Make no mistake, Rheims is a vile traitor to the Crown. Also, a betrayer of his own crew as well\nHe was carrying out a very important mission when he switched alliances\nWhen one of his men warned me of his betrayal, we almost prevent this calamity. Sadly, the poor fellow was already at death's door, and he couldn't tell me where Rheims was heading\nWe know they stopped at the pirate encampment to re-supply. You should go to this pirate camp and if ",
"Raoul Rheims",
", is still there, arrest him. If he is not, discover what you can.",
"Understood. However, facing pirates is a dangerous task. I do expect to be well compensated.",
"And you will be. I will pay you 5000 gold now and 5000 when you return with the betrayer. Good luck!",
"A fair price. I shall be on my way, sir.",
"How is it you're free? What's happened? What of the guards?",
"I'm sorry, but I was jailed unfairly. It wasn't going to be stuck there forever. When I regained my weapon, I only sought my freedom.",
"I am sorry, ",
"! There has been a terrible mistake. My soldiers were meant to arrest a French spy. They clearly mistook you for him.",
"Thanks for you apologies, sir, I wasn't sure I'd ever be free again.",
"I applaud your skill and cunning. It does you honor, but the jailer should be hanged for letting you escape!",
"I am afraid you don't have anybody to hang, sir. He's already been dealt with.",
"The jailer is your affair. Now, if you would kindly explain the reason why I found myself in jail.",
"Sir, I'd like to speak on his behalf. He says he was quite proficient with the guns in his day. I have need of a good gunner, and with your permission, I'd like to take him on.",
"Hmm. I suppose leniency can be considered, ",
", but this jailer serves the colony - I can't just let him go.",
"Then tell me your price for replacing him, sir.",
"1000 gold will be enough.",
"A fair bargain, sir. I accept",
"Ah well. This is more than I was expecting. It will be better if this jailer serves you.",
"Take him, but you may regret it later, I hear he is a drunkard.",
"I'll take your warning into consideration, sir. Now, perhaps you'd like to explain to me why I was arrested.",
"You're too bloodthirsty, but that may be what's required for this world - your hand will never waver with pity.",
"I hope so, sir. Now if you may, please tell me why you had me arrested?",
"A terrible mistake. A terrible mistake. My soldiers were sent to arrest a French spy. My agents assured me that he was in the tavern at that very moment\nIt appears he had already gone, and my soldiers arrested you instead.",
"Well, one mystery is solved. You can imagine my distress when I found myself in that dark scary place.",
"A terrible mistake. A terrible mistake. My soldiers were sent to arrest a spy\nMy agents assured me that he was in the tavern at that very moment. \nIt appears he had already gone, and my soldiers arrested you instead.",
"Well, one mystery is solved.",
"Good. Now that we are finished with all this nonsense, I'd like you to come with me. We have important matters to discuss.",
"Of course, sir.",
"Please accept my apologies once again for the actions of my soldiers. I think this money will prove to you how sorry I am about this incident.",
"Thank you, sir. For my part, I thank you for your kindness to me.",

};
